// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(construct_coreFFI)
import construct_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_construct_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_construct_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol ClassicCryptoCoreProtocol : AnyObject {
    
    func decryptMessage(sessionId: String, ephemeralPublicKey: [UInt8], messageNumber: UInt32, content: String) throws  -> String
    
    func encryptMessage(sessionId: String, plaintext: String) throws  -> EncryptedMessageComponents
    
    func exportPrivateKeysJson() throws  -> String
    
    func exportRegistrationBundleJson() throws  -> String
    
    func exportSessionJson(contactId: String) throws  -> String
    
    func getAllSessionContactIds()  -> [String]
    
    func importSessionJson(contactId: String, sessionJson: String) throws  -> String
    
    func initReceivingSession(contactId: String, recipientBundle: [UInt8], firstMessage: [UInt8]) throws  -> SessionInitResult
    
    func initSession(contactId: String, recipientBundle: [UInt8]) throws  -> String
    
    func removeSession(contactId: String)  -> Bool
    
}

open class ClassicCryptoCore:
    ClassicCryptoCoreProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_construct_core_fn_clone_classiccryptocore(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_construct_core_fn_free_classiccryptocore(pointer, $0) }
    }

    

    
open func decryptMessage(sessionId: String, ephemeralPublicKey: [UInt8], messageNumber: UInt32, content: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_construct_core_fn_method_classiccryptocore_decrypt_message(self.uniffiClonePointer(),
        FfiConverterString.lower(sessionId),
        FfiConverterSequenceUInt8.lower(ephemeralPublicKey),
        FfiConverterUInt32.lower(messageNumber),
        FfiConverterString.lower(content),$0
    )
})
}
    
open func encryptMessage(sessionId: String, plaintext: String)throws  -> EncryptedMessageComponents {
    return try  FfiConverterTypeEncryptedMessageComponents.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_construct_core_fn_method_classiccryptocore_encrypt_message(self.uniffiClonePointer(),
        FfiConverterString.lower(sessionId),
        FfiConverterString.lower(plaintext),$0
    )
})
}
    
open func exportPrivateKeysJson()throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_construct_core_fn_method_classiccryptocore_export_private_keys_json(self.uniffiClonePointer(),$0
    )
})
}
    
open func exportRegistrationBundleJson()throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_construct_core_fn_method_classiccryptocore_export_registration_bundle_json(self.uniffiClonePointer(),$0
    )
})
}
    
open func exportSessionJson(contactId: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_construct_core_fn_method_classiccryptocore_export_session_json(self.uniffiClonePointer(),
        FfiConverterString.lower(contactId),$0
    )
})
}
    
open func getAllSessionContactIds() -> [String] {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_construct_core_fn_method_classiccryptocore_get_all_session_contact_ids(self.uniffiClonePointer(),$0
    )
})
}
    
open func importSessionJson(contactId: String, sessionJson: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_construct_core_fn_method_classiccryptocore_import_session_json(self.uniffiClonePointer(),
        FfiConverterString.lower(contactId),
        FfiConverterString.lower(sessionJson),$0
    )
})
}
    
open func initReceivingSession(contactId: String, recipientBundle: [UInt8], firstMessage: [UInt8])throws  -> SessionInitResult {
    return try  FfiConverterTypeSessionInitResult.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_construct_core_fn_method_classiccryptocore_init_receiving_session(self.uniffiClonePointer(),
        FfiConverterString.lower(contactId),
        FfiConverterSequenceUInt8.lower(recipientBundle),
        FfiConverterSequenceUInt8.lower(firstMessage),$0
    )
})
}
    
open func initSession(contactId: String, recipientBundle: [UInt8])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_construct_core_fn_method_classiccryptocore_init_session(self.uniffiClonePointer(),
        FfiConverterString.lower(contactId),
        FfiConverterSequenceUInt8.lower(recipientBundle),$0
    )
})
}
    
open func removeSession(contactId: String) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_construct_core_fn_method_classiccryptocore_remove_session(self.uniffiClonePointer(),
        FfiConverterString.lower(contactId),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClassicCryptoCore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ClassicCryptoCore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ClassicCryptoCore {
        return ClassicCryptoCore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ClassicCryptoCore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClassicCryptoCore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ClassicCryptoCore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicCryptoCore_lift(_ pointer: UnsafeMutableRawPointer) throws -> ClassicCryptoCore {
    return try FfiConverterTypeClassicCryptoCore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicCryptoCore_lower(_ value: ClassicCryptoCore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeClassicCryptoCore.lower(value)
}




public protocol TrafficProtectionManagerProtocol : AnyObject {
    
    func currentIntervalMs()  -> UInt64
    
    func generateDummy()  -> [UInt8]
    
    func getMetrics()  -> EnergyMetrics
    
    func isCurrentlyActive()  -> Bool
    
    func recordRealMessageSent() 
    
    func resetMetrics() 
    
    func shouldSendDummy()  -> Bool
    
    func updateBatteryLevel(level: Float) 
    
}

open class TrafficProtectionManager:
    TrafficProtectionManagerProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_construct_core_fn_clone_trafficprotectionmanager(self.pointer, $0) }
    }
public convenience init(config: CoverTrafficConfig) {
    let pointer =
        try! rustCall() {
    uniffi_construct_core_fn_constructor_trafficprotectionmanager_new(
        FfiConverterTypeCoverTrafficConfig.lower(config),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_construct_core_fn_free_trafficprotectionmanager(pointer, $0) }
    }

    

    
open func currentIntervalMs() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_construct_core_fn_method_trafficprotectionmanager_current_interval_ms(self.uniffiClonePointer(),$0
    )
})
}
    
open func generateDummy() -> [UInt8] {
    return try!  FfiConverterSequenceUInt8.lift(try! rustCall() {
    uniffi_construct_core_fn_method_trafficprotectionmanager_generate_dummy(self.uniffiClonePointer(),$0
    )
})
}
    
open func getMetrics() -> EnergyMetrics {
    return try!  FfiConverterTypeEnergyMetrics.lift(try! rustCall() {
    uniffi_construct_core_fn_method_trafficprotectionmanager_get_metrics(self.uniffiClonePointer(),$0
    )
})
}
    
open func isCurrentlyActive() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_construct_core_fn_method_trafficprotectionmanager_is_currently_active(self.uniffiClonePointer(),$0
    )
})
}
    
open func recordRealMessageSent() {try! rustCall() {
    uniffi_construct_core_fn_method_trafficprotectionmanager_record_real_message_sent(self.uniffiClonePointer(),$0
    )
}
}
    
open func resetMetrics() {try! rustCall() {
    uniffi_construct_core_fn_method_trafficprotectionmanager_reset_metrics(self.uniffiClonePointer(),$0
    )
}
}
    
open func shouldSendDummy() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_construct_core_fn_method_trafficprotectionmanager_should_send_dummy(self.uniffiClonePointer(),$0
    )
})
}
    
open func updateBatteryLevel(level: Float) {try! rustCall() {
    uniffi_construct_core_fn_method_trafficprotectionmanager_update_battery_level(self.uniffiClonePointer(),
        FfiConverterFloat.lower(level),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTrafficProtectionManager: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = TrafficProtectionManager

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> TrafficProtectionManager {
        return TrafficProtectionManager(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: TrafficProtectionManager) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TrafficProtectionManager {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: TrafficProtectionManager, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrafficProtectionManager_lift(_ pointer: UnsafeMutableRawPointer) throws -> TrafficProtectionManager {
    return try FfiConverterTypeTrafficProtectionManager.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrafficProtectionManager_lower(_ value: TrafficProtectionManager) -> UnsafeMutableRawPointer {
    return FfiConverterTypeTrafficProtectionManager.lower(value)
}


public struct CoverTrafficConfig {
    public var enabled: Bool
    public var batteryLevelThreshold: Float
    public var minIntervalMs: UInt64
    public var maxIntervalMs: UInt64
    public var messageSize: UInt64
    public var coalesceWithRealMessages: Bool
    public var coalesceWindowMs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(enabled: Bool, batteryLevelThreshold: Float, minIntervalMs: UInt64, maxIntervalMs: UInt64, messageSize: UInt64, coalesceWithRealMessages: Bool, coalesceWindowMs: UInt64) {
        self.enabled = enabled
        self.batteryLevelThreshold = batteryLevelThreshold
        self.minIntervalMs = minIntervalMs
        self.maxIntervalMs = maxIntervalMs
        self.messageSize = messageSize
        self.coalesceWithRealMessages = coalesceWithRealMessages
        self.coalesceWindowMs = coalesceWindowMs
    }
}



extension CoverTrafficConfig: Equatable, Hashable {
    public static func ==(lhs: CoverTrafficConfig, rhs: CoverTrafficConfig) -> Bool {
        if lhs.enabled != rhs.enabled {
            return false
        }
        if lhs.batteryLevelThreshold != rhs.batteryLevelThreshold {
            return false
        }
        if lhs.minIntervalMs != rhs.minIntervalMs {
            return false
        }
        if lhs.maxIntervalMs != rhs.maxIntervalMs {
            return false
        }
        if lhs.messageSize != rhs.messageSize {
            return false
        }
        if lhs.coalesceWithRealMessages != rhs.coalesceWithRealMessages {
            return false
        }
        if lhs.coalesceWindowMs != rhs.coalesceWindowMs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(enabled)
        hasher.combine(batteryLevelThreshold)
        hasher.combine(minIntervalMs)
        hasher.combine(maxIntervalMs)
        hasher.combine(messageSize)
        hasher.combine(coalesceWithRealMessages)
        hasher.combine(coalesceWindowMs)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoverTrafficConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoverTrafficConfig {
        return
            try CoverTrafficConfig(
                enabled: FfiConverterBool.read(from: &buf), 
                batteryLevelThreshold: FfiConverterFloat.read(from: &buf), 
                minIntervalMs: FfiConverterUInt64.read(from: &buf), 
                maxIntervalMs: FfiConverterUInt64.read(from: &buf), 
                messageSize: FfiConverterUInt64.read(from: &buf), 
                coalesceWithRealMessages: FfiConverterBool.read(from: &buf), 
                coalesceWindowMs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: CoverTrafficConfig, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.enabled, into: &buf)
        FfiConverterFloat.write(value.batteryLevelThreshold, into: &buf)
        FfiConverterUInt64.write(value.minIntervalMs, into: &buf)
        FfiConverterUInt64.write(value.maxIntervalMs, into: &buf)
        FfiConverterUInt64.write(value.messageSize, into: &buf)
        FfiConverterBool.write(value.coalesceWithRealMessages, into: &buf)
        FfiConverterUInt64.write(value.coalesceWindowMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoverTrafficConfig_lift(_ buf: RustBuffer) throws -> CoverTrafficConfig {
    return try FfiConverterTypeCoverTrafficConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoverTrafficConfig_lower(_ value: CoverTrafficConfig) -> RustBuffer {
    return FfiConverterTypeCoverTrafficConfig.lower(value)
}


public struct EncryptedMessageComponents {
    public var ephemeralPublicKey: [UInt8]
    public var messageNumber: UInt32
    public var content: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(ephemeralPublicKey: [UInt8], messageNumber: UInt32, content: String) {
        self.ephemeralPublicKey = ephemeralPublicKey
        self.messageNumber = messageNumber
        self.content = content
    }
}



extension EncryptedMessageComponents: Equatable, Hashable {
    public static func ==(lhs: EncryptedMessageComponents, rhs: EncryptedMessageComponents) -> Bool {
        if lhs.ephemeralPublicKey != rhs.ephemeralPublicKey {
            return false
        }
        if lhs.messageNumber != rhs.messageNumber {
            return false
        }
        if lhs.content != rhs.content {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(ephemeralPublicKey)
        hasher.combine(messageNumber)
        hasher.combine(content)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncryptedMessageComponents: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncryptedMessageComponents {
        return
            try EncryptedMessageComponents(
                ephemeralPublicKey: FfiConverterSequenceUInt8.read(from: &buf), 
                messageNumber: FfiConverterUInt32.read(from: &buf), 
                content: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: EncryptedMessageComponents, into buf: inout [UInt8]) {
        FfiConverterSequenceUInt8.write(value.ephemeralPublicKey, into: &buf)
        FfiConverterUInt32.write(value.messageNumber, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedMessageComponents_lift(_ buf: RustBuffer) throws -> EncryptedMessageComponents {
    return try FfiConverterTypeEncryptedMessageComponents.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedMessageComponents_lower(_ value: EncryptedMessageComponents) -> RustBuffer {
    return FfiConverterTypeEncryptedMessageComponents.lower(value)
}


public struct EnergyMetrics {
    public var dummiesSent: UInt64
    public var coalescedCount: UInt64
    public var batterySkipped: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(dummiesSent: UInt64, coalescedCount: UInt64, batterySkipped: UInt64) {
        self.dummiesSent = dummiesSent
        self.coalescedCount = coalescedCount
        self.batterySkipped = batterySkipped
    }
}



extension EnergyMetrics: Equatable, Hashable {
    public static func ==(lhs: EnergyMetrics, rhs: EnergyMetrics) -> Bool {
        if lhs.dummiesSent != rhs.dummiesSent {
            return false
        }
        if lhs.coalescedCount != rhs.coalescedCount {
            return false
        }
        if lhs.batterySkipped != rhs.batterySkipped {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(dummiesSent)
        hasher.combine(coalescedCount)
        hasher.combine(batterySkipped)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEnergyMetrics: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EnergyMetrics {
        return
            try EnergyMetrics(
                dummiesSent: FfiConverterUInt64.read(from: &buf), 
                coalescedCount: FfiConverterUInt64.read(from: &buf), 
                batterySkipped: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: EnergyMetrics, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.dummiesSent, into: &buf)
        FfiConverterUInt64.write(value.coalescedCount, into: &buf)
        FfiConverterUInt64.write(value.batterySkipped, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEnergyMetrics_lift(_ buf: RustBuffer) throws -> EnergyMetrics {
    return try FfiConverterTypeEnergyMetrics.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEnergyMetrics_lower(_ value: EnergyMetrics) -> RustBuffer {
    return FfiConverterTypeEnergyMetrics.lower(value)
}


public struct PrivateKeysJson {
    public var identitySecret: String
    public var signingSecret: String
    public var signedPrekeySecret: String
    public var prekeySignature: String
    public var suiteId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(identitySecret: String, signingSecret: String, signedPrekeySecret: String, prekeySignature: String, suiteId: String) {
        self.identitySecret = identitySecret
        self.signingSecret = signingSecret
        self.signedPrekeySecret = signedPrekeySecret
        self.prekeySignature = prekeySignature
        self.suiteId = suiteId
    }
}



extension PrivateKeysJson: Equatable, Hashable {
    public static func ==(lhs: PrivateKeysJson, rhs: PrivateKeysJson) -> Bool {
        if lhs.identitySecret != rhs.identitySecret {
            return false
        }
        if lhs.signingSecret != rhs.signingSecret {
            return false
        }
        if lhs.signedPrekeySecret != rhs.signedPrekeySecret {
            return false
        }
        if lhs.prekeySignature != rhs.prekeySignature {
            return false
        }
        if lhs.suiteId != rhs.suiteId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(identitySecret)
        hasher.combine(signingSecret)
        hasher.combine(signedPrekeySecret)
        hasher.combine(prekeySignature)
        hasher.combine(suiteId)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePrivateKeysJson: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrivateKeysJson {
        return
            try PrivateKeysJson(
                identitySecret: FfiConverterString.read(from: &buf), 
                signingSecret: FfiConverterString.read(from: &buf), 
                signedPrekeySecret: FfiConverterString.read(from: &buf), 
                prekeySignature: FfiConverterString.read(from: &buf), 
                suiteId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: PrivateKeysJson, into buf: inout [UInt8]) {
        FfiConverterString.write(value.identitySecret, into: &buf)
        FfiConverterString.write(value.signingSecret, into: &buf)
        FfiConverterString.write(value.signedPrekeySecret, into: &buf)
        FfiConverterString.write(value.prekeySignature, into: &buf)
        FfiConverterString.write(value.suiteId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrivateKeysJson_lift(_ buf: RustBuffer) throws -> PrivateKeysJson {
    return try FfiConverterTypePrivateKeysJson.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrivateKeysJson_lower(_ value: PrivateKeysJson) -> RustBuffer {
    return FfiConverterTypePrivateKeysJson.lower(value)
}


public struct RegistrationBundleJson {
    public var identityPublic: String
    public var signedPrekeyPublic: String
    public var signature: String
    public var verifyingKey: String
    public var suiteId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(identityPublic: String, signedPrekeyPublic: String, signature: String, verifyingKey: String, suiteId: String) {
        self.identityPublic = identityPublic
        self.signedPrekeyPublic = signedPrekeyPublic
        self.signature = signature
        self.verifyingKey = verifyingKey
        self.suiteId = suiteId
    }
}



extension RegistrationBundleJson: Equatable, Hashable {
    public static func ==(lhs: RegistrationBundleJson, rhs: RegistrationBundleJson) -> Bool {
        if lhs.identityPublic != rhs.identityPublic {
            return false
        }
        if lhs.signedPrekeyPublic != rhs.signedPrekeyPublic {
            return false
        }
        if lhs.signature != rhs.signature {
            return false
        }
        if lhs.verifyingKey != rhs.verifyingKey {
            return false
        }
        if lhs.suiteId != rhs.suiteId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(identityPublic)
        hasher.combine(signedPrekeyPublic)
        hasher.combine(signature)
        hasher.combine(verifyingKey)
        hasher.combine(suiteId)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRegistrationBundleJson: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RegistrationBundleJson {
        return
            try RegistrationBundleJson(
                identityPublic: FfiConverterString.read(from: &buf), 
                signedPrekeyPublic: FfiConverterString.read(from: &buf), 
                signature: FfiConverterString.read(from: &buf), 
                verifyingKey: FfiConverterString.read(from: &buf), 
                suiteId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: RegistrationBundleJson, into buf: inout [UInt8]) {
        FfiConverterString.write(value.identityPublic, into: &buf)
        FfiConverterString.write(value.signedPrekeyPublic, into: &buf)
        FfiConverterString.write(value.signature, into: &buf)
        FfiConverterString.write(value.verifyingKey, into: &buf)
        FfiConverterString.write(value.suiteId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRegistrationBundleJson_lift(_ buf: RustBuffer) throws -> RegistrationBundleJson {
    return try FfiConverterTypeRegistrationBundleJson.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRegistrationBundleJson_lower(_ value: RegistrationBundleJson) -> RustBuffer {
    return FfiConverterTypeRegistrationBundleJson.lower(value)
}


public struct SessionInitResult {
    public var sessionId: String
    public var decryptedMessage: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sessionId: String, decryptedMessage: String) {
        self.sessionId = sessionId
        self.decryptedMessage = decryptedMessage
    }
}



extension SessionInitResult: Equatable, Hashable {
    public static func ==(lhs: SessionInitResult, rhs: SessionInitResult) -> Bool {
        if lhs.sessionId != rhs.sessionId {
            return false
        }
        if lhs.decryptedMessage != rhs.decryptedMessage {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sessionId)
        hasher.combine(decryptedMessage)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionInitResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionInitResult {
        return
            try SessionInitResult(
                sessionId: FfiConverterString.read(from: &buf), 
                decryptedMessage: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SessionInitResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.sessionId, into: &buf)
        FfiConverterString.write(value.decryptedMessage, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionInitResult_lift(_ buf: RustBuffer) throws -> SessionInitResult {
    return try FfiConverterTypeSessionInitResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionInitResult_lower(_ value: SessionInitResult) -> RustBuffer {
    return FfiConverterTypeSessionInitResult.lower(value)
}


public struct TimingConfig {
    public var heartbeatIntervalSec: UInt64
    public var heartbeatJitterMs: UInt64
    public var maxSendDelayMs: UInt64
    public var enabled: Bool
    public var batteryAware: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(heartbeatIntervalSec: UInt64, heartbeatJitterMs: UInt64, maxSendDelayMs: UInt64, enabled: Bool, batteryAware: Bool) {
        self.heartbeatIntervalSec = heartbeatIntervalSec
        self.heartbeatJitterMs = heartbeatJitterMs
        self.maxSendDelayMs = maxSendDelayMs
        self.enabled = enabled
        self.batteryAware = batteryAware
    }
}



extension TimingConfig: Equatable, Hashable {
    public static func ==(lhs: TimingConfig, rhs: TimingConfig) -> Bool {
        if lhs.heartbeatIntervalSec != rhs.heartbeatIntervalSec {
            return false
        }
        if lhs.heartbeatJitterMs != rhs.heartbeatJitterMs {
            return false
        }
        if lhs.maxSendDelayMs != rhs.maxSendDelayMs {
            return false
        }
        if lhs.enabled != rhs.enabled {
            return false
        }
        if lhs.batteryAware != rhs.batteryAware {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(heartbeatIntervalSec)
        hasher.combine(heartbeatJitterMs)
        hasher.combine(maxSendDelayMs)
        hasher.combine(enabled)
        hasher.combine(batteryAware)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTimingConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TimingConfig {
        return
            try TimingConfig(
                heartbeatIntervalSec: FfiConverterUInt64.read(from: &buf), 
                heartbeatJitterMs: FfiConverterUInt64.read(from: &buf), 
                maxSendDelayMs: FfiConverterUInt64.read(from: &buf), 
                enabled: FfiConverterBool.read(from: &buf), 
                batteryAware: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: TimingConfig, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.heartbeatIntervalSec, into: &buf)
        FfiConverterUInt64.write(value.heartbeatJitterMs, into: &buf)
        FfiConverterUInt64.write(value.maxSendDelayMs, into: &buf)
        FfiConverterBool.write(value.enabled, into: &buf)
        FfiConverterBool.write(value.batteryAware, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimingConfig_lift(_ buf: RustBuffer) throws -> TimingConfig {
    return try FfiConverterTypeTimingConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimingConfig_lower(_ value: TimingConfig) -> RustBuffer {
    return FfiConverterTypeTimingConfig.lower(value)
}


public enum CryptoError {

    
    
    case InitializationFailed(message: String)
    
    case SessionNotFound(message: String)
    
    case SessionInitializationFailed(message: String)
    
    case EncryptionFailed(message: String)
    
    case DecryptionFailed(message: String)
    
    case InvalidKeyData(message: String)
    
    case InvalidCiphertext(message: String)
    
    case SerializationFailed(message: String)
    
    case MessagePackDeserializationFailed(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCryptoError: FfiConverterRustBuffer {
    typealias SwiftType = CryptoError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CryptoError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InitializationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .SessionNotFound(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .SessionInitializationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .EncryptionFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .DecryptionFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .InvalidKeyData(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .InvalidCiphertext(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .SerializationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .MessagePackDeserializationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CryptoError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .InitializationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .SessionNotFound(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .SessionInitializationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .EncryptionFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .DecryptionFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .InvalidKeyData(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .InvalidCiphertext(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))
        case .SerializationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(8))
        case .MessagePackDeserializationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(9))

        
        }
    }
}


extension CryptoError: Equatable, Hashable {}

extension CryptoError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]

    public static func write(_ value: [UInt8], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt8.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt8] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt8]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt8.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}
public func batteryAwareJitterMs(baseMs: UInt64, maxJitterMs: UInt64, batteryLevel: Float) -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_construct_core_fn_func_battery_aware_jitter_ms(
        FfiConverterUInt64.lower(baseMs),
        FfiConverterUInt64.lower(maxJitterMs),
        FfiConverterFloat.lower(batteryLevel),$0
    )
})
}
public func createCryptoCore()throws  -> ClassicCryptoCore {
    return try  FfiConverterTypeClassicCryptoCore.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_construct_core_fn_func_create_crypto_core($0
    )
})
}
public func createCryptoCoreFromKeysJson(keysJson: String)throws  -> ClassicCryptoCore {
    return try  FfiConverterTypeClassicCryptoCore.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_construct_core_fn_func_create_crypto_core_from_keys_json(
        FfiConverterString.lower(keysJson),$0
    )
})
}
public func generateDummyMessage(size: UInt64) -> [UInt8] {
    return try!  FfiConverterSequenceUInt8.lift(try! rustCall() {
    uniffi_construct_core_fn_func_generate_dummy_message(
        FfiConverterUInt64.lower(size),$0
    )
})
}
public func heartbeatIntervalMs(baseIntervalSec: UInt64) -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_construct_core_fn_func_heartbeat_interval_ms(
        FfiConverterUInt64.lower(baseIntervalSec),$0
    )
})
}
public func isDummyMessage(data: [UInt8]) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_construct_core_fn_func_is_dummy_message(
        FfiConverterSequenceUInt8.lower(data),$0
    )
})
}
public func jitteredIntervalMs(baseMs: UInt64, jitterMs: UInt64) -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_construct_core_fn_func_jittered_interval_ms(
        FfiConverterUInt64.lower(baseMs),
        FfiConverterUInt64.lower(jitterMs),$0
    )
})
}
public func randomSendDelayMs(maxDelayMs: UInt64) -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_construct_core_fn_func_random_send_delay_ms(
        FfiConverterUInt64.lower(maxDelayMs),$0
    )
})
}
public func recommendedSendDelayMs(isHighPriority: Bool, batteryLevel: Float) -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_construct_core_fn_func_recommended_send_delay_ms(
        FfiConverterBool.lower(isHighPriority),
        FfiConverterFloat.lower(batteryLevel),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_construct_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_construct_core_checksum_func_battery_aware_jitter_ms() != 100) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_create_crypto_core() != 59945) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_create_crypto_core_from_keys_json() != 4455) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_generate_dummy_message() != 52724) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_heartbeat_interval_ms() != 51594) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_is_dummy_message() != 41979) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_jittered_interval_ms() != 6840) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_random_send_delay_ms() != 9943) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_recommended_send_delay_ms() != 24315) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_decrypt_message() != 52559) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_encrypt_message() != 30896) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_export_private_keys_json() != 39134) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_export_registration_bundle_json() != 50804) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_export_session_json() != 53072) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_get_all_session_contact_ids() != 7165) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_import_session_json() != 35033) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_init_receiving_session() != 47586) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_init_session() != 28133) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_remove_session() != 58665) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_trafficprotectionmanager_current_interval_ms() != 19714) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_trafficprotectionmanager_generate_dummy() != 43371) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_trafficprotectionmanager_get_metrics() != 15186) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_trafficprotectionmanager_is_currently_active() != 1132) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_trafficprotectionmanager_record_real_message_sent() != 8261) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_trafficprotectionmanager_reset_metrics() != 12014) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_trafficprotectionmanager_should_send_dummy() != 15293) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_trafficprotectionmanager_update_battery_level() != 64806) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_constructor_trafficprotectionmanager_new() != 37511) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all