//
//  NetworkError.swift
//  Construct Messenger
//
//  Created by Maxim Eliseyev on 13.12.2025.
//

import Foundation

enum NetworkError: Error, LocalizedError {
    case connectionFailed
    case disconnected
    case notConnected          // Not connected to server
    case invalidMessage
    case encodingFailed
    case decodingFailed
    case serverError(message: String, responseBody: String?)

    var errorDescription: String? {
        switch self {
        case .connectionFailed: return "Failed to connect to server"
        case .disconnected: return "Connection lost"
        case .notConnected: return "Not connected to server"
        case .invalidMessage: return "Invalid message format"
        case .encodingFailed: return "Failed to encode message"
        case .decodingFailed: return "Failed to decode message"
        case .serverError(let message, _): return "Server error: \(message)"
        }
    }
}

/// Client-side errors generated by our own networking layer.
/// Using a distinct type (instead of RPCError with a magic message string) lets
/// callers distinguish our errors from library-generated ones via `is` checks.
enum GRPCClientError: Error {
    /// The client-side deadline elapsed before the server responded.
    /// Distinct from a server `.deadlineExceeded` — the connection is healthy.
    case clientSideTimeout
}

// MARK: - grpc-swift message fragments (grpc-swift v2 / NIOTS)
//
// These are substrings that appear in RPCError.message for specific grpc-swift
// transport conditions. They are intentionally centralised here so a library
// upgrade that changes the wording only needs a single fix.
//
// Last verified against: grpc-swift 2.x / NIOTransportServices HTTP2ClientTransport
enum GRPCMessages {
    /// WebSocket UPGRADE returned a non-101 / non-200 response.
    /// Emitted by HTTP2ClientTransport when a transparent HTTP proxy intercepts the upgrade.
    static let nonHttpUpgrade   = "non-200"
    static let httpStatusCode   = "http status code"
    static let unexpectedHttp   = "unexpected"  // combined with `http` in the same message
    /// HTTP/2 stream closed before a response was received.
    static let streamClosed     = "stream"      // combined with `closed` in the same message
    /// The GRPCClient was shut down (beginGracefulShutdown called).
    static let channelClosed    = "channel is closed"
    /// Connection refused on the local ICE proxy address.
    static let localProxyAddr   = "127.0.0.1"
    /// Our own client-side deadline message — kept for legacy log matching only.
    /// Code should use `GRPCClientError.clientSideTimeout` for new checks.
    static let requestTimedOut  = "request timed out"
}
