// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(construct_engineFFI)
import construct_engineFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_construct_engine_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_construct_engine_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureConstructEngineInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol ConstructEngineProtocol: AnyObject, Sendable {
    
    /**
     * Dispatch a UI event to the engine (non-blocking, sync).
     */
    func dispatch(event: UiEvent) 
    
    /**
     * Graceful shutdown. Waits up to 5s for in-flight sends.
     */
    func shutdown() 
    
    /**
     * Start the engine (non-blocking). Spawns internal tokio runtime.
     * Networking begins after `PlatformReady` event is dispatched.
     */
    func start() throws 
    
}
open class ConstructEngine: ConstructEngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_construct_engine_fn_clone_constructengine(self.handle, $0) }
    }
    /**
     * Create the engine. Does not start networking yet.
     */
public convenience init(config: EngineConfig, callback: EngineCallback)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeEngineError_lift) {
    uniffi_construct_engine_fn_constructor_constructengine_new(
        FfiConverterTypeEngineConfig_lower(config),
        FfiConverterCallbackInterfaceEngineCallback_lower(callback),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_construct_engine_fn_free_constructengine(handle, $0) }
    }

    

    
    /**
     * Dispatch a UI event to the engine (non-blocking, sync).
     */
open func dispatch(event: UiEvent)  {try! rustCall() {
    uniffi_construct_engine_fn_method_constructengine_dispatch(
            self.uniffiCloneHandle(),
        FfiConverterTypeUiEvent_lower(event),$0
    )
}
}
    
    /**
     * Graceful shutdown. Waits up to 5s for in-flight sends.
     */
open func shutdown()  {try! rustCall() {
    uniffi_construct_engine_fn_method_constructengine_shutdown(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Start the engine (non-blocking). Spawns internal tokio runtime.
     * Networking begins after `PlatformReady` event is dispatched.
     */
open func start()throws   {try rustCallWithError(FfiConverterTypeEngineError_lift) {
    uniffi_construct_engine_fn_method_constructengine_start(
            self.uniffiCloneHandle(),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConstructEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ConstructEngine

    public static func lift(_ handle: UInt64) throws -> ConstructEngine {
        return ConstructEngine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ConstructEngine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConstructEngine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ConstructEngine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConstructEngine_lift(_ handle: UInt64) throws -> ConstructEngine {
    return try FfiConverterTypeConstructEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConstructEngine_lower(_ value: ConstructEngine) -> UInt64 {
    return FfiConverterTypeConstructEngine.lower(value)
}




public struct EngineConfig: Equatable, Hashable {
    public var serverHost: String
    public var serverPort: UInt16
    /**
     * Device ID (UUID string). Empty on fresh install.
     */
    public var myDeviceId: String
    /**
     * User ID (hash of identity public key). Empty on fresh install.
     */
    public var myUserId: String
    /**
     * CFE-encoded private key blob (CfePrivateKeysV1). Empty on fresh install.
     */
    public var keysCfeData: Data
    /**
     * Auth token from Keychain. None on fresh install.
     */
    public var authToken: String?
    public var verifyCerts: Bool
    public var useMasque: Bool
    public var masqueHost: String?
    public var masquePort: UInt16?
    public var eventBuffer: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(serverHost: String, serverPort: UInt16, 
        /**
         * Device ID (UUID string). Empty on fresh install.
         */myDeviceId: String, 
        /**
         * User ID (hash of identity public key). Empty on fresh install.
         */myUserId: String, 
        /**
         * CFE-encoded private key blob (CfePrivateKeysV1). Empty on fresh install.
         */keysCfeData: Data, 
        /**
         * Auth token from Keychain. None on fresh install.
         */authToken: String?, verifyCerts: Bool, useMasque: Bool, masqueHost: String?, masquePort: UInt16?, eventBuffer: UInt64) {
        self.serverHost = serverHost
        self.serverPort = serverPort
        self.myDeviceId = myDeviceId
        self.myUserId = myUserId
        self.keysCfeData = keysCfeData
        self.authToken = authToken
        self.verifyCerts = verifyCerts
        self.useMasque = useMasque
        self.masqueHost = masqueHost
        self.masquePort = masquePort
        self.eventBuffer = eventBuffer
    }

    
}

#if compiler(>=6)
extension EngineConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineConfig {
        return
            try EngineConfig(
                serverHost: FfiConverterString.read(from: &buf), 
                serverPort: FfiConverterUInt16.read(from: &buf), 
                myDeviceId: FfiConverterString.read(from: &buf), 
                myUserId: FfiConverterString.read(from: &buf), 
                keysCfeData: FfiConverterData.read(from: &buf), 
                authToken: FfiConverterOptionString.read(from: &buf), 
                verifyCerts: FfiConverterBool.read(from: &buf), 
                useMasque: FfiConverterBool.read(from: &buf), 
                masqueHost: FfiConverterOptionString.read(from: &buf), 
                masquePort: FfiConverterOptionUInt16.read(from: &buf), 
                eventBuffer: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: EngineConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.serverHost, into: &buf)
        FfiConverterUInt16.write(value.serverPort, into: &buf)
        FfiConverterString.write(value.myDeviceId, into: &buf)
        FfiConverterString.write(value.myUserId, into: &buf)
        FfiConverterData.write(value.keysCfeData, into: &buf)
        FfiConverterOptionString.write(value.authToken, into: &buf)
        FfiConverterBool.write(value.verifyCerts, into: &buf)
        FfiConverterBool.write(value.useMasque, into: &buf)
        FfiConverterOptionString.write(value.masqueHost, into: &buf)
        FfiConverterOptionUInt16.write(value.masquePort, into: &buf)
        FfiConverterUInt64.write(value.eventBuffer, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineConfig_lift(_ buf: RustBuffer) throws -> EngineConfig {
    return try FfiConverterTypeEngineConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineConfig_lower(_ value: EngineConfig) -> RustBuffer {
    return FfiConverterTypeEngineConfig.lower(value)
}


public struct IceCandidate: Equatable, Hashable {
    public var candidateType: CandidateType
    public var address: String
    public var priority: UInt32
    public var foundation: String?
    public var interfaceName: String?
    public var transport: String
    public var generation: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(candidateType: CandidateType, address: String, priority: UInt32, foundation: String?, interfaceName: String?, transport: String, generation: UInt32) {
        self.candidateType = candidateType
        self.address = address
        self.priority = priority
        self.foundation = foundation
        self.interfaceName = interfaceName
        self.transport = transport
        self.generation = generation
    }

    
}

#if compiler(>=6)
extension IceCandidate: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeICECandidate: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IceCandidate {
        return
            try IceCandidate(
                candidateType: FfiConverterTypeCandidateType.read(from: &buf), 
                address: FfiConverterString.read(from: &buf), 
                priority: FfiConverterUInt32.read(from: &buf), 
                foundation: FfiConverterOptionString.read(from: &buf), 
                interfaceName: FfiConverterOptionString.read(from: &buf), 
                transport: FfiConverterString.read(from: &buf), 
                generation: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: IceCandidate, into buf: inout [UInt8]) {
        FfiConverterTypeCandidateType.write(value.candidateType, into: &buf)
        FfiConverterString.write(value.address, into: &buf)
        FfiConverterUInt32.write(value.priority, into: &buf)
        FfiConverterOptionString.write(value.foundation, into: &buf)
        FfiConverterOptionString.write(value.interfaceName, into: &buf)
        FfiConverterString.write(value.transport, into: &buf)
        FfiConverterUInt32.write(value.generation, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeICECandidate_lift(_ buf: RustBuffer) throws -> IceCandidate {
    return try FfiConverterTypeICECandidate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeICECandidate_lower(_ value: IceCandidate) -> RustBuffer {
    return FfiConverterTypeICECandidate.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum CandidateType: Equatable, Hashable {
    
    case localLan
    case publicIp
    case relay
    case ipv6LinkLocal
    case ipv6Global



}

#if compiler(>=6)
extension CandidateType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCandidateType: FfiConverterRustBuffer {
    typealias SwiftType = CandidateType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CandidateType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .localLan
        
        case 2: return .publicIp
        
        case 3: return .relay
        
        case 4: return .ipv6LinkLocal
        
        case 5: return .ipv6Global
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CandidateType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .localLan:
            writeInt(&buf, Int32(1))
        
        
        case .publicIp:
            writeInt(&buf, Int32(2))
        
        
        case .relay:
            writeInt(&buf, Int32(3))
        
        
        case .ipv6LinkLocal:
            writeInt(&buf, Int32(4))
        
        
        case .ipv6Global:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCandidateType_lift(_ buf: RustBuffer) throws -> CandidateType {
    return try FfiConverterTypeCandidateType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCandidateType_lower(_ value: CandidateType) -> RustBuffer {
    return FfiConverterTypeCandidateType.lower(value)
}



public enum EngineError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Transport(message: String
    )
    case Tls(message: String
    )
    case Grpc(code: UInt32, message: String
    )
    case Crypto(message: String
    )
    case Config(message: String
    )
    case AlreadyRunning
    case NotRunning
    case Timeout
    case Unauthenticated(message: String
    )
    case Internal(message: String
    )

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension EngineError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineError: FfiConverterRustBuffer {
    typealias SwiftType = EngineError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Transport(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Tls(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Grpc(
            code: try FfiConverterUInt32.read(from: &buf), 
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Crypto(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Config(
            message: try FfiConverterString.read(from: &buf)
            )
        case 6: return .AlreadyRunning
        case 7: return .NotRunning
        case 8: return .Timeout
        case 9: return .Unauthenticated(
            message: try FfiConverterString.read(from: &buf)
            )
        case 10: return .Internal(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EngineError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Transport(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Tls(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Grpc(code,message):
            writeInt(&buf, Int32(3))
            FfiConverterUInt32.write(code, into: &buf)
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Crypto(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Config(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        
        case .AlreadyRunning:
            writeInt(&buf, Int32(6))
        
        
        case .NotRunning:
            writeInt(&buf, Int32(7))
        
        
        case .Timeout:
            writeInt(&buf, Int32(8))
        
        
        case let .Unauthenticated(message):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Internal(message):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineError_lift(_ buf: RustBuffer) throws -> EngineError {
    return try FfiConverterTypeEngineError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineError_lower(_ value: EngineError) -> RustBuffer {
    return FfiConverterTypeEngineError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum PlatformAction: Equatable, Hashable {
    
    case saveKeychain(key: String, data: Data
    )
    case loadKeychain(key: String
    )
    case deleteKeychain(key: String
    )
    case setAuthToken(userId: String, accessToken: String, refreshToken: String, expiresAt: Int64
    )
    case clearAuth
    case registrationComplete(userId: String, deviceId: String
    )
    case saveMessage(envelopeBytes: Data, senderId: String, conversationId: String, timestamp: Int64
    )
    case updateMessageStatus(localId: String, status: UInt8
    )
    case displayMessage(messageId: String, plaintext: Data, senderId: String, conversationId: String, timestamp: Int64
    )
    case deliveryReceipt(messageId: String, conversationId: String, timestamp: Int64
    )
    case sessionEstablished(contactId: String, sessionId: String
    )
    case sessionError(contactId: String, message: String
    )
    case preKeyBundleReady(userId: String, bundleBytes: Data
    )
    case otpksUploaded(uploaded: UInt32, serverCount: UInt32
    )
    case preKeyCountUpdated(count: UInt32, recommendedMinimum: UInt32
    )
    case spkRotated(keyId: UInt32
    )
    case streamReady(streamCursor: String?
    )
    case streamError(message: String
    )
    case incomingCall(callId: String, callerId: String, signalBytes: Data
    )
    case callSignalReceived(callId: String, signalBytes: Data
    )
    case connectionStateChanged(connected: Bool
    )
    case networkError(message: String
    )
    case log(level: String, message: String
    )
    case showNotification(messageId: String, senderId: String, conversationId: String, preview: Data?, timestamp: Int64
    )
    case backgroundFetchComplete(decryptedCount: UInt32, hadErrors: Bool
    )
    case p2pStatusReport(peerId: String, connected: Bool, latencyMs: UInt32?, isRelay: Bool
    )
    case userFound(userId: String, username: String
    )
    case userNotFound(query: String
    )



}

#if compiler(>=6)
extension PlatformAction: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePlatformAction: FfiConverterRustBuffer {
    typealias SwiftType = PlatformAction

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PlatformAction {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .saveKeychain(key: try FfiConverterString.read(from: &buf), data: try FfiConverterData.read(from: &buf)
        )
        
        case 2: return .loadKeychain(key: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .deleteKeychain(key: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .setAuthToken(userId: try FfiConverterString.read(from: &buf), accessToken: try FfiConverterString.read(from: &buf), refreshToken: try FfiConverterString.read(from: &buf), expiresAt: try FfiConverterInt64.read(from: &buf)
        )
        
        case 5: return .clearAuth
        
        case 6: return .registrationComplete(userId: try FfiConverterString.read(from: &buf), deviceId: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .saveMessage(envelopeBytes: try FfiConverterData.read(from: &buf), senderId: try FfiConverterString.read(from: &buf), conversationId: try FfiConverterString.read(from: &buf), timestamp: try FfiConverterInt64.read(from: &buf)
        )
        
        case 8: return .updateMessageStatus(localId: try FfiConverterString.read(from: &buf), status: try FfiConverterUInt8.read(from: &buf)
        )
        
        case 9: return .displayMessage(messageId: try FfiConverterString.read(from: &buf), plaintext: try FfiConverterData.read(from: &buf), senderId: try FfiConverterString.read(from: &buf), conversationId: try FfiConverterString.read(from: &buf), timestamp: try FfiConverterInt64.read(from: &buf)
        )
        
        case 10: return .deliveryReceipt(messageId: try FfiConverterString.read(from: &buf), conversationId: try FfiConverterString.read(from: &buf), timestamp: try FfiConverterInt64.read(from: &buf)
        )
        
        case 11: return .sessionEstablished(contactId: try FfiConverterString.read(from: &buf), sessionId: try FfiConverterString.read(from: &buf)
        )
        
        case 12: return .sessionError(contactId: try FfiConverterString.read(from: &buf), message: try FfiConverterString.read(from: &buf)
        )
        
        case 13: return .preKeyBundleReady(userId: try FfiConverterString.read(from: &buf), bundleBytes: try FfiConverterData.read(from: &buf)
        )
        
        case 14: return .otpksUploaded(uploaded: try FfiConverterUInt32.read(from: &buf), serverCount: try FfiConverterUInt32.read(from: &buf)
        )
        
        case 15: return .preKeyCountUpdated(count: try FfiConverterUInt32.read(from: &buf), recommendedMinimum: try FfiConverterUInt32.read(from: &buf)
        )
        
        case 16: return .spkRotated(keyId: try FfiConverterUInt32.read(from: &buf)
        )
        
        case 17: return .streamReady(streamCursor: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 18: return .streamError(message: try FfiConverterString.read(from: &buf)
        )
        
        case 19: return .incomingCall(callId: try FfiConverterString.read(from: &buf), callerId: try FfiConverterString.read(from: &buf), signalBytes: try FfiConverterData.read(from: &buf)
        )
        
        case 20: return .callSignalReceived(callId: try FfiConverterString.read(from: &buf), signalBytes: try FfiConverterData.read(from: &buf)
        )
        
        case 21: return .connectionStateChanged(connected: try FfiConverterBool.read(from: &buf)
        )
        
        case 22: return .networkError(message: try FfiConverterString.read(from: &buf)
        )
        
        case 23: return .log(level: try FfiConverterString.read(from: &buf), message: try FfiConverterString.read(from: &buf)
        )
        
        case 24: return .showNotification(messageId: try FfiConverterString.read(from: &buf), senderId: try FfiConverterString.read(from: &buf), conversationId: try FfiConverterString.read(from: &buf), preview: try FfiConverterOptionData.read(from: &buf), timestamp: try FfiConverterInt64.read(from: &buf)
        )
        
        case 25: return .backgroundFetchComplete(decryptedCount: try FfiConverterUInt32.read(from: &buf), hadErrors: try FfiConverterBool.read(from: &buf)
        )
        
        case 26: return .p2pStatusReport(peerId: try FfiConverterString.read(from: &buf), connected: try FfiConverterBool.read(from: &buf), latencyMs: try FfiConverterOptionUInt32.read(from: &buf), isRelay: try FfiConverterBool.read(from: &buf)
        )
        
        case 27: return .userFound(userId: try FfiConverterString.read(from: &buf), username: try FfiConverterString.read(from: &buf)
        )
        
        case 28: return .userNotFound(query: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PlatformAction, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .saveKeychain(key,data):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(key, into: &buf)
            FfiConverterData.write(data, into: &buf)
            
        
        case let .loadKeychain(key):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(key, into: &buf)
            
        
        case let .deleteKeychain(key):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(key, into: &buf)
            
        
        case let .setAuthToken(userId,accessToken,refreshToken,expiresAt):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(userId, into: &buf)
            FfiConverterString.write(accessToken, into: &buf)
            FfiConverterString.write(refreshToken, into: &buf)
            FfiConverterInt64.write(expiresAt, into: &buf)
            
        
        case .clearAuth:
            writeInt(&buf, Int32(5))
        
        
        case let .registrationComplete(userId,deviceId):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(userId, into: &buf)
            FfiConverterString.write(deviceId, into: &buf)
            
        
        case let .saveMessage(envelopeBytes,senderId,conversationId,timestamp):
            writeInt(&buf, Int32(7))
            FfiConverterData.write(envelopeBytes, into: &buf)
            FfiConverterString.write(senderId, into: &buf)
            FfiConverterString.write(conversationId, into: &buf)
            FfiConverterInt64.write(timestamp, into: &buf)
            
        
        case let .updateMessageStatus(localId,status):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(localId, into: &buf)
            FfiConverterUInt8.write(status, into: &buf)
            
        
        case let .displayMessage(messageId,plaintext,senderId,conversationId,timestamp):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(messageId, into: &buf)
            FfiConverterData.write(plaintext, into: &buf)
            FfiConverterString.write(senderId, into: &buf)
            FfiConverterString.write(conversationId, into: &buf)
            FfiConverterInt64.write(timestamp, into: &buf)
            
        
        case let .deliveryReceipt(messageId,conversationId,timestamp):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(messageId, into: &buf)
            FfiConverterString.write(conversationId, into: &buf)
            FfiConverterInt64.write(timestamp, into: &buf)
            
        
        case let .sessionEstablished(contactId,sessionId):
            writeInt(&buf, Int32(11))
            FfiConverterString.write(contactId, into: &buf)
            FfiConverterString.write(sessionId, into: &buf)
            
        
        case let .sessionError(contactId,message):
            writeInt(&buf, Int32(12))
            FfiConverterString.write(contactId, into: &buf)
            FfiConverterString.write(message, into: &buf)
            
        
        case let .preKeyBundleReady(userId,bundleBytes):
            writeInt(&buf, Int32(13))
            FfiConverterString.write(userId, into: &buf)
            FfiConverterData.write(bundleBytes, into: &buf)
            
        
        case let .otpksUploaded(uploaded,serverCount):
            writeInt(&buf, Int32(14))
            FfiConverterUInt32.write(uploaded, into: &buf)
            FfiConverterUInt32.write(serverCount, into: &buf)
            
        
        case let .preKeyCountUpdated(count,recommendedMinimum):
            writeInt(&buf, Int32(15))
            FfiConverterUInt32.write(count, into: &buf)
            FfiConverterUInt32.write(recommendedMinimum, into: &buf)
            
        
        case let .spkRotated(keyId):
            writeInt(&buf, Int32(16))
            FfiConverterUInt32.write(keyId, into: &buf)
            
        
        case let .streamReady(streamCursor):
            writeInt(&buf, Int32(17))
            FfiConverterOptionString.write(streamCursor, into: &buf)
            
        
        case let .streamError(message):
            writeInt(&buf, Int32(18))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .incomingCall(callId,callerId,signalBytes):
            writeInt(&buf, Int32(19))
            FfiConverterString.write(callId, into: &buf)
            FfiConverterString.write(callerId, into: &buf)
            FfiConverterData.write(signalBytes, into: &buf)
            
        
        case let .callSignalReceived(callId,signalBytes):
            writeInt(&buf, Int32(20))
            FfiConverterString.write(callId, into: &buf)
            FfiConverterData.write(signalBytes, into: &buf)
            
        
        case let .connectionStateChanged(connected):
            writeInt(&buf, Int32(21))
            FfiConverterBool.write(connected, into: &buf)
            
        
        case let .networkError(message):
            writeInt(&buf, Int32(22))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .log(level,message):
            writeInt(&buf, Int32(23))
            FfiConverterString.write(level, into: &buf)
            FfiConverterString.write(message, into: &buf)
            
        
        case let .showNotification(messageId,senderId,conversationId,preview,timestamp):
            writeInt(&buf, Int32(24))
            FfiConverterString.write(messageId, into: &buf)
            FfiConverterString.write(senderId, into: &buf)
            FfiConverterString.write(conversationId, into: &buf)
            FfiConverterOptionData.write(preview, into: &buf)
            FfiConverterInt64.write(timestamp, into: &buf)
            
        
        case let .backgroundFetchComplete(decryptedCount,hadErrors):
            writeInt(&buf, Int32(25))
            FfiConverterUInt32.write(decryptedCount, into: &buf)
            FfiConverterBool.write(hadErrors, into: &buf)
            
        
        case let .p2pStatusReport(peerId,connected,latencyMs,isRelay):
            writeInt(&buf, Int32(26))
            FfiConverterString.write(peerId, into: &buf)
            FfiConverterBool.write(connected, into: &buf)
            FfiConverterOptionUInt32.write(latencyMs, into: &buf)
            FfiConverterBool.write(isRelay, into: &buf)
            
        
        case let .userFound(userId,username):
            writeInt(&buf, Int32(27))
            FfiConverterString.write(userId, into: &buf)
            FfiConverterString.write(username, into: &buf)
            
        
        case let .userNotFound(query):
            writeInt(&buf, Int32(28))
            FfiConverterString.write(query, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlatformAction_lift(_ buf: RustBuffer) throws -> PlatformAction {
    return try FfiConverterTypePlatformAction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlatformAction_lower(_ value: PlatformAction) -> RustBuffer {
    return FfiConverterTypePlatformAction.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum UiEvent: Equatable, Hashable {
    
    case registerDevice(username: String?, deviceId: String
    )
    case authenticate(deviceId: String, challengeResponse: Data, signingKey: Data
    )
    case refreshToken(refreshToken: String
    )
    case logout
    case fetchPreKeyBundle(userId: String, deviceId: String?
    )
    case uploadOtpks(deviceId: String, count: UInt32
    )
    case getPreKeyCount(deviceId: String
    )
    case rotateSignedPreKey(deviceId: String
    )
    case openMessageStream(conversationIds: [String], sinceCursor: String?
    )
    case closeMessageStream
    case sendMessage(contactId: String, plaintext: Data, localId: String, conversationId: String
    )
    case ackMessage(messageId: String, messageNumber: UInt64
    )
    case initSessionInitiator(contactId: String
    )
    case searchUser(query: String
    )
    case signal(callId: String, signalBytes: Data
    )
    case registerPushToken(token: String, platform: String
    )
    case backgroundPush(sinceCursor: String?
    )
    case keychainResult(key: String, data: Data?
    )
    case platformReady
    case p2pHandoffInitiate(peerId: String, candidates: [IceCandidate]
    )
    case p2pHandoffAck(sessionId: String, success: Bool, candidates: [IceCandidate], measuredLatencyMs: UInt32?
    )
    case p2pStatusReport(peerId: String, connected: Bool, latencyMs: UInt32?, isRelay: Bool
    )



}

#if compiler(>=6)
extension UiEvent: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUiEvent: FfiConverterRustBuffer {
    typealias SwiftType = UiEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UiEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .registerDevice(username: try FfiConverterOptionString.read(from: &buf), deviceId: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .authenticate(deviceId: try FfiConverterString.read(from: &buf), challengeResponse: try FfiConverterData.read(from: &buf), signingKey: try FfiConverterData.read(from: &buf)
        )
        
        case 3: return .refreshToken(refreshToken: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .logout
        
        case 5: return .fetchPreKeyBundle(userId: try FfiConverterString.read(from: &buf), deviceId: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 6: return .uploadOtpks(deviceId: try FfiConverterString.read(from: &buf), count: try FfiConverterUInt32.read(from: &buf)
        )
        
        case 7: return .getPreKeyCount(deviceId: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .rotateSignedPreKey(deviceId: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .openMessageStream(conversationIds: try FfiConverterSequenceString.read(from: &buf), sinceCursor: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 10: return .closeMessageStream
        
        case 11: return .sendMessage(contactId: try FfiConverterString.read(from: &buf), plaintext: try FfiConverterData.read(from: &buf), localId: try FfiConverterString.read(from: &buf), conversationId: try FfiConverterString.read(from: &buf)
        )
        
        case 12: return .ackMessage(messageId: try FfiConverterString.read(from: &buf), messageNumber: try FfiConverterUInt64.read(from: &buf)
        )
        
        case 13: return .initSessionInitiator(contactId: try FfiConverterString.read(from: &buf)
        )
        
        case 14: return .searchUser(query: try FfiConverterString.read(from: &buf)
        )
        
        case 15: return .signal(callId: try FfiConverterString.read(from: &buf), signalBytes: try FfiConverterData.read(from: &buf)
        )
        
        case 16: return .registerPushToken(token: try FfiConverterString.read(from: &buf), platform: try FfiConverterString.read(from: &buf)
        )
        
        case 17: return .backgroundPush(sinceCursor: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 18: return .keychainResult(key: try FfiConverterString.read(from: &buf), data: try FfiConverterOptionData.read(from: &buf)
        )
        
        case 19: return .platformReady
        
        case 20: return .p2pHandoffInitiate(peerId: try FfiConverterString.read(from: &buf), candidates: try FfiConverterSequenceTypeICECandidate.read(from: &buf)
        )
        
        case 21: return .p2pHandoffAck(sessionId: try FfiConverterString.read(from: &buf), success: try FfiConverterBool.read(from: &buf), candidates: try FfiConverterSequenceTypeICECandidate.read(from: &buf), measuredLatencyMs: try FfiConverterOptionUInt32.read(from: &buf)
        )
        
        case 22: return .p2pStatusReport(peerId: try FfiConverterString.read(from: &buf), connected: try FfiConverterBool.read(from: &buf), latencyMs: try FfiConverterOptionUInt32.read(from: &buf), isRelay: try FfiConverterBool.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: UiEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .registerDevice(username,deviceId):
            writeInt(&buf, Int32(1))
            FfiConverterOptionString.write(username, into: &buf)
            FfiConverterString.write(deviceId, into: &buf)
            
        
        case let .authenticate(deviceId,challengeResponse,signingKey):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(deviceId, into: &buf)
            FfiConverterData.write(challengeResponse, into: &buf)
            FfiConverterData.write(signingKey, into: &buf)
            
        
        case let .refreshToken(refreshToken):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(refreshToken, into: &buf)
            
        
        case .logout:
            writeInt(&buf, Int32(4))
        
        
        case let .fetchPreKeyBundle(userId,deviceId):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(userId, into: &buf)
            FfiConverterOptionString.write(deviceId, into: &buf)
            
        
        case let .uploadOtpks(deviceId,count):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(deviceId, into: &buf)
            FfiConverterUInt32.write(count, into: &buf)
            
        
        case let .getPreKeyCount(deviceId):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(deviceId, into: &buf)
            
        
        case let .rotateSignedPreKey(deviceId):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(deviceId, into: &buf)
            
        
        case let .openMessageStream(conversationIds,sinceCursor):
            writeInt(&buf, Int32(9))
            FfiConverterSequenceString.write(conversationIds, into: &buf)
            FfiConverterOptionString.write(sinceCursor, into: &buf)
            
        
        case .closeMessageStream:
            writeInt(&buf, Int32(10))
        
        
        case let .sendMessage(contactId,plaintext,localId,conversationId):
            writeInt(&buf, Int32(11))
            FfiConverterString.write(contactId, into: &buf)
            FfiConverterData.write(plaintext, into: &buf)
            FfiConverterString.write(localId, into: &buf)
            FfiConverterString.write(conversationId, into: &buf)
            
        
        case let .ackMessage(messageId,messageNumber):
            writeInt(&buf, Int32(12))
            FfiConverterString.write(messageId, into: &buf)
            FfiConverterUInt64.write(messageNumber, into: &buf)
            
        
        case let .initSessionInitiator(contactId):
            writeInt(&buf, Int32(13))
            FfiConverterString.write(contactId, into: &buf)
            
        
        case let .searchUser(query):
            writeInt(&buf, Int32(14))
            FfiConverterString.write(query, into: &buf)
            
        
        case let .signal(callId,signalBytes):
            writeInt(&buf, Int32(15))
            FfiConverterString.write(callId, into: &buf)
            FfiConverterData.write(signalBytes, into: &buf)
            
        
        case let .registerPushToken(token,platform):
            writeInt(&buf, Int32(16))
            FfiConverterString.write(token, into: &buf)
            FfiConverterString.write(platform, into: &buf)
            
        
        case let .backgroundPush(sinceCursor):
            writeInt(&buf, Int32(17))
            FfiConverterOptionString.write(sinceCursor, into: &buf)
            
        
        case let .keychainResult(key,data):
            writeInt(&buf, Int32(18))
            FfiConverterString.write(key, into: &buf)
            FfiConverterOptionData.write(data, into: &buf)
            
        
        case .platformReady:
            writeInt(&buf, Int32(19))
        
        
        case let .p2pHandoffInitiate(peerId,candidates):
            writeInt(&buf, Int32(20))
            FfiConverterString.write(peerId, into: &buf)
            FfiConverterSequenceTypeICECandidate.write(candidates, into: &buf)
            
        
        case let .p2pHandoffAck(sessionId,success,candidates,measuredLatencyMs):
            writeInt(&buf, Int32(21))
            FfiConverterString.write(sessionId, into: &buf)
            FfiConverterBool.write(success, into: &buf)
            FfiConverterSequenceTypeICECandidate.write(candidates, into: &buf)
            FfiConverterOptionUInt32.write(measuredLatencyMs, into: &buf)
            
        
        case let .p2pStatusReport(peerId,connected,latencyMs,isRelay):
            writeInt(&buf, Int32(22))
            FfiConverterString.write(peerId, into: &buf)
            FfiConverterBool.write(connected, into: &buf)
            FfiConverterOptionUInt32.write(latencyMs, into: &buf)
            FfiConverterBool.write(isRelay, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUiEvent_lift(_ buf: RustBuffer) throws -> UiEvent {
    return try FfiConverterTypeUiEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUiEvent_lower(_ value: UiEvent) -> RustBuffer {
    return FfiConverterTypeUiEvent.lower(value)
}





public protocol EngineCallback: AnyObject, Sendable {
    
    func onAction(action: PlatformAction) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceEngineCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceEngineCallback] = [UniffiVTableCallbackInterfaceEngineCallback(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceEngineCallback.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface EngineCallback: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceEngineCallback.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface EngineCallback: handle missing in uniffiClone")
            }
        },
        onAction: { (
            uniffiHandle: UInt64,
            action: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEngineCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onAction(
                     action: try FfiConverterTypePlatformAction_lift(action)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitEngineCallback() {
    uniffi_construct_engine_fn_init_callback_vtable_enginecallback(UniffiCallbackInterfaceEngineCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceEngineCallback {
    fileprivate static let handleMap = UniffiHandleMap<EngineCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceEngineCallback : FfiConverter {
    typealias SwiftType = EngineCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceEngineCallback_lift(_ handle: UInt64) throws -> EngineCallback {
    return try FfiConverterCallbackInterfaceEngineCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceEngineCallback_lower(_ v: EngineCallback) -> UInt64 {
    return FfiConverterCallbackInterfaceEngineCallback.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt16: FfiConverterRustBuffer {
    typealias SwiftType = UInt16?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt16.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt16.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeICECandidate: FfiConverterRustBuffer {
    typealias SwiftType = [IceCandidate]

    public static func write(_ value: [IceCandidate], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeICECandidate.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [IceCandidate] {
        let len: Int32 = try readInt(&buf)
        var seq = [IceCandidate]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeICECandidate.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_construct_engine_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_construct_engine_checksum_method_constructengine_dispatch() != 4659) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_engine_checksum_method_constructengine_shutdown() != 5952) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_engine_checksum_method_constructengine_start() != 53644) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_engine_checksum_constructor_constructengine_new() != 41091) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_engine_checksum_method_enginecallback_on_action() != 48492) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitEngineCallback()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureConstructEngineInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all