// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(construct_coreFFI)
import construct_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_construct_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_construct_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureConstructCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol ClassicCryptoCoreProtocol: AnyObject, Sendable {
    
    func decryptMessage(sessionId: String, ephemeralPublicKey: [UInt8], messageNumber: UInt32, content: String) throws  -> String
    
    func encryptMessage(sessionId: String, plaintext: String) throws  -> EncryptedMessageComponents
    
    func exportPrivateKeysJson() throws  -> String
    
    func exportRegistrationBundleJson() throws  -> String
    
    func exportSessionJson(contactId: String) throws  -> String
    
    func getAllSessionContactIds()  -> [String]
    
    func importSessionJson(contactId: String, sessionJson: String) throws  -> String
    
    func initReceivingSession(contactId: String, recipientBundle: [UInt8], firstMessage: [UInt8]) throws  -> SessionInitResult
    
    func initSession(contactId: String, recipientBundle: [UInt8]) throws  -> String
    
    func removeSession(contactId: String)  -> Bool
    
    func setLocalUserId(userId: String) 
    
    func signBundleData(bundleDataJson: [UInt8]) throws  -> String
    
}
open class ClassicCryptoCore: ClassicCryptoCoreProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_construct_core_fn_clone_classiccryptocore(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_construct_core_fn_free_classiccryptocore(handle, $0) }
    }

    

    
open func decryptMessage(sessionId: String, ephemeralPublicKey: [UInt8], messageNumber: UInt32, content: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_construct_core_fn_method_classiccryptocore_decrypt_message(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(sessionId),
        FfiConverterSequenceUInt8.lower(ephemeralPublicKey),
        FfiConverterUInt32.lower(messageNumber),
        FfiConverterString.lower(content),$0
    )
})
}
    
open func encryptMessage(sessionId: String, plaintext: String)throws  -> EncryptedMessageComponents  {
    return try  FfiConverterTypeEncryptedMessageComponents_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_construct_core_fn_method_classiccryptocore_encrypt_message(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(sessionId),
        FfiConverterString.lower(plaintext),$0
    )
})
}
    
open func exportPrivateKeysJson()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_construct_core_fn_method_classiccryptocore_export_private_keys_json(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func exportRegistrationBundleJson()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_construct_core_fn_method_classiccryptocore_export_registration_bundle_json(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func exportSessionJson(contactId: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_construct_core_fn_method_classiccryptocore_export_session_json(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(contactId),$0
    )
})
}
    
open func getAllSessionContactIds() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_construct_core_fn_method_classiccryptocore_get_all_session_contact_ids(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func importSessionJson(contactId: String, sessionJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_construct_core_fn_method_classiccryptocore_import_session_json(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(contactId),
        FfiConverterString.lower(sessionJson),$0
    )
})
}
    
open func initReceivingSession(contactId: String, recipientBundle: [UInt8], firstMessage: [UInt8])throws  -> SessionInitResult  {
    return try  FfiConverterTypeSessionInitResult_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_construct_core_fn_method_classiccryptocore_init_receiving_session(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(contactId),
        FfiConverterSequenceUInt8.lower(recipientBundle),
        FfiConverterSequenceUInt8.lower(firstMessage),$0
    )
})
}
    
open func initSession(contactId: String, recipientBundle: [UInt8])throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_construct_core_fn_method_classiccryptocore_init_session(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(contactId),
        FfiConverterSequenceUInt8.lower(recipientBundle),$0
    )
})
}
    
open func removeSession(contactId: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_construct_core_fn_method_classiccryptocore_remove_session(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(contactId),$0
    )
})
}
    
open func setLocalUserId(userId: String)  {try! rustCall() {
    uniffi_construct_core_fn_method_classiccryptocore_set_local_user_id(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(userId),$0
    )
}
}
    
open func signBundleData(bundleDataJson: [UInt8])throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_construct_core_fn_method_classiccryptocore_sign_bundle_data(
            self.uniffiCloneHandle(),
        FfiConverterSequenceUInt8.lower(bundleDataJson),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClassicCryptoCore: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ClassicCryptoCore

    public static func lift(_ handle: UInt64) throws -> ClassicCryptoCore {
        return ClassicCryptoCore(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ClassicCryptoCore) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClassicCryptoCore {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ClassicCryptoCore, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicCryptoCore_lift(_ handle: UInt64) throws -> ClassicCryptoCore {
    return try FfiConverterTypeClassicCryptoCore.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicCryptoCore_lower(_ value: ClassicCryptoCore) -> UInt64 {
    return FfiConverterTypeClassicCryptoCore.lower(value)
}






public protocol TrafficProtectionManagerProtocol: AnyObject, Sendable {
    
    func currentIntervalMs()  -> UInt64
    
    func generateDummy()  -> [UInt8]
    
    func getMetrics()  -> EnergyMetrics
    
    func isCurrentlyActive()  -> Bool
    
    func recordRealMessageSent() 
    
    func resetMetrics() 
    
    func shouldSendDummy()  -> Bool
    
    func updateBatteryLevel(level: Float) 
    
}
open class TrafficProtectionManager: TrafficProtectionManagerProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_construct_core_fn_clone_trafficprotectionmanager(self.handle, $0) }
    }
public convenience init(config: CoverTrafficConfig) {
    let handle =
        try! rustCall() {
    uniffi_construct_core_fn_constructor_trafficprotectionmanager_new(
        FfiConverterTypeCoverTrafficConfig_lower(config),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_construct_core_fn_free_trafficprotectionmanager(handle, $0) }
    }

    

    
open func currentIntervalMs() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_construct_core_fn_method_trafficprotectionmanager_current_interval_ms(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func generateDummy() -> [UInt8]  {
    return try!  FfiConverterSequenceUInt8.lift(try! rustCall() {
    uniffi_construct_core_fn_method_trafficprotectionmanager_generate_dummy(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getMetrics() -> EnergyMetrics  {
    return try!  FfiConverterTypeEnergyMetrics_lift(try! rustCall() {
    uniffi_construct_core_fn_method_trafficprotectionmanager_get_metrics(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func isCurrentlyActive() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_construct_core_fn_method_trafficprotectionmanager_is_currently_active(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func recordRealMessageSent()  {try! rustCall() {
    uniffi_construct_core_fn_method_trafficprotectionmanager_record_real_message_sent(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func resetMetrics()  {try! rustCall() {
    uniffi_construct_core_fn_method_trafficprotectionmanager_reset_metrics(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func shouldSendDummy() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_construct_core_fn_method_trafficprotectionmanager_should_send_dummy(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func updateBatteryLevel(level: Float)  {try! rustCall() {
    uniffi_construct_core_fn_method_trafficprotectionmanager_update_battery_level(
            self.uniffiCloneHandle(),
        FfiConverterFloat.lower(level),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTrafficProtectionManager: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = TrafficProtectionManager

    public static func lift(_ handle: UInt64) throws -> TrafficProtectionManager {
        return TrafficProtectionManager(unsafeFromHandle: handle)
    }

    public static func lower(_ value: TrafficProtectionManager) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TrafficProtectionManager {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: TrafficProtectionManager, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrafficProtectionManager_lift(_ handle: UInt64) throws -> TrafficProtectionManager {
    return try FfiConverterTypeTrafficProtectionManager.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrafficProtectionManager_lower(_ value: TrafficProtectionManager) -> UInt64 {
    return FfiConverterTypeTrafficProtectionManager.lower(value)
}




/**
 * Токены аутентификации (JWT)
 */
public struct AuthTokens: Equatable, Hashable {
    /**
     * Access token (JWT, живёт 1 час)
     */
    public var accessToken: String
    /**
     * Refresh token (JWT, живёт 30 дней)
     */
    public var refreshToken: String
    /**
     * Unix timestamp когда истекает access token
     */
    public var expiresAt: Int64
    /**
     * User ID (UUID)
     */
    public var userId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Access token (JWT, живёт 1 час)
         */accessToken: String, 
        /**
         * Refresh token (JWT, живёт 30 дней)
         */refreshToken: String, 
        /**
         * Unix timestamp когда истекает access token
         */expiresAt: Int64, 
        /**
         * User ID (UUID)
         */userId: String) {
        self.accessToken = accessToken
        self.refreshToken = refreshToken
        self.expiresAt = expiresAt
        self.userId = userId
    }

    
}

#if compiler(>=6)
extension AuthTokens: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAuthTokens: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AuthTokens {
        return
            try AuthTokens(
                accessToken: FfiConverterString.read(from: &buf), 
                refreshToken: FfiConverterString.read(from: &buf), 
                expiresAt: FfiConverterInt64.read(from: &buf), 
                userId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AuthTokens, into buf: inout [UInt8]) {
        FfiConverterString.write(value.accessToken, into: &buf)
        FfiConverterString.write(value.refreshToken, into: &buf)
        FfiConverterInt64.write(value.expiresAt, into: &buf)
        FfiConverterString.write(value.userId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthTokens_lift(_ buf: RustBuffer) throws -> AuthTokens {
    return try FfiConverterTypeAuthTokens.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthTokens_lower(_ value: AuthTokens) -> RustBuffer {
    return FfiConverterTypeAuthTokens.lower(value)
}


public struct CoverTrafficConfig: Equatable, Hashable {
    public var enabled: Bool
    public var batteryLevelThreshold: Float
    public var minIntervalMs: UInt64
    public var maxIntervalMs: UInt64
    public var messageSize: UInt64
    public var coalesceWithRealMessages: Bool
    public var coalesceWindowMs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(enabled: Bool, batteryLevelThreshold: Float, minIntervalMs: UInt64, maxIntervalMs: UInt64, messageSize: UInt64, coalesceWithRealMessages: Bool, coalesceWindowMs: UInt64) {
        self.enabled = enabled
        self.batteryLevelThreshold = batteryLevelThreshold
        self.minIntervalMs = minIntervalMs
        self.maxIntervalMs = maxIntervalMs
        self.messageSize = messageSize
        self.coalesceWithRealMessages = coalesceWithRealMessages
        self.coalesceWindowMs = coalesceWindowMs
    }

    
}

#if compiler(>=6)
extension CoverTrafficConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoverTrafficConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoverTrafficConfig {
        return
            try CoverTrafficConfig(
                enabled: FfiConverterBool.read(from: &buf), 
                batteryLevelThreshold: FfiConverterFloat.read(from: &buf), 
                minIntervalMs: FfiConverterUInt64.read(from: &buf), 
                maxIntervalMs: FfiConverterUInt64.read(from: &buf), 
                messageSize: FfiConverterUInt64.read(from: &buf), 
                coalesceWithRealMessages: FfiConverterBool.read(from: &buf), 
                coalesceWindowMs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: CoverTrafficConfig, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.enabled, into: &buf)
        FfiConverterFloat.write(value.batteryLevelThreshold, into: &buf)
        FfiConverterUInt64.write(value.minIntervalMs, into: &buf)
        FfiConverterUInt64.write(value.maxIntervalMs, into: &buf)
        FfiConverterUInt64.write(value.messageSize, into: &buf)
        FfiConverterBool.write(value.coalesceWithRealMessages, into: &buf)
        FfiConverterUInt64.write(value.coalesceWindowMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoverTrafficConfig_lift(_ buf: RustBuffer) throws -> CoverTrafficConfig {
    return try FfiConverterTypeCoverTrafficConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoverTrafficConfig_lower(_ value: CoverTrafficConfig) -> RustBuffer {
    return FfiConverterTypeCoverTrafficConfig.lower(value)
}


public struct EncryptedMessageComponents: Equatable, Hashable {
    public var ephemeralPublicKey: [UInt8]
    public var messageNumber: UInt32
    public var content: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(ephemeralPublicKey: [UInt8], messageNumber: UInt32, content: String) {
        self.ephemeralPublicKey = ephemeralPublicKey
        self.messageNumber = messageNumber
        self.content = content
    }

    
}

#if compiler(>=6)
extension EncryptedMessageComponents: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncryptedMessageComponents: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncryptedMessageComponents {
        return
            try EncryptedMessageComponents(
                ephemeralPublicKey: FfiConverterSequenceUInt8.read(from: &buf), 
                messageNumber: FfiConverterUInt32.read(from: &buf), 
                content: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: EncryptedMessageComponents, into buf: inout [UInt8]) {
        FfiConverterSequenceUInt8.write(value.ephemeralPublicKey, into: &buf)
        FfiConverterUInt32.write(value.messageNumber, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedMessageComponents_lift(_ buf: RustBuffer) throws -> EncryptedMessageComponents {
    return try FfiConverterTypeEncryptedMessageComponents.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedMessageComponents_lower(_ value: EncryptedMessageComponents) -> RustBuffer {
    return FfiConverterTypeEncryptedMessageComponents.lower(value)
}


public struct EnergyMetrics: Equatable, Hashable {
    public var dummiesSent: UInt64
    public var coalescedCount: UInt64
    public var batterySkipped: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(dummiesSent: UInt64, coalescedCount: UInt64, batterySkipped: UInt64) {
        self.dummiesSent = dummiesSent
        self.coalescedCount = coalescedCount
        self.batterySkipped = batterySkipped
    }

    
}

#if compiler(>=6)
extension EnergyMetrics: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEnergyMetrics: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EnergyMetrics {
        return
            try EnergyMetrics(
                dummiesSent: FfiConverterUInt64.read(from: &buf), 
                coalescedCount: FfiConverterUInt64.read(from: &buf), 
                batterySkipped: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: EnergyMetrics, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.dummiesSent, into: &buf)
        FfiConverterUInt64.write(value.coalescedCount, into: &buf)
        FfiConverterUInt64.write(value.batterySkipped, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEnergyMetrics_lift(_ buf: RustBuffer) throws -> EnergyMetrics {
    return try FfiConverterTypeEnergyMetrics.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEnergyMetrics_lower(_ value: EnergyMetrics) -> RustBuffer {
    return FfiConverterTypeEnergyMetrics.lower(value)
}


public struct EphemeralKeyPair: Equatable, Hashable {
    public var secretKey: [UInt8]
    public var publicKey: [UInt8]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(secretKey: [UInt8], publicKey: [UInt8]) {
        self.secretKey = secretKey
        self.publicKey = publicKey
    }

    
}

#if compiler(>=6)
extension EphemeralKeyPair: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEphemeralKeyPair: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EphemeralKeyPair {
        return
            try EphemeralKeyPair(
                secretKey: FfiConverterSequenceUInt8.read(from: &buf), 
                publicKey: FfiConverterSequenceUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: EphemeralKeyPair, into buf: inout [UInt8]) {
        FfiConverterSequenceUInt8.write(value.secretKey, into: &buf)
        FfiConverterSequenceUInt8.write(value.publicKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEphemeralKeyPair_lift(_ buf: RustBuffer) throws -> EphemeralKeyPair {
    return try FfiConverterTypeEphemeralKeyPair.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEphemeralKeyPair_lower(_ value: EphemeralKeyPair) -> RustBuffer {
    return FfiConverterTypeEphemeralKeyPair.lower(value)
}


public struct InviteSignature: Equatable, Hashable {
    public var signature: [UInt8]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(signature: [UInt8]) {
        self.signature = signature
    }

    
}

#if compiler(>=6)
extension InviteSignature: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeInviteSignature: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> InviteSignature {
        return
            try InviteSignature(
                signature: FfiConverterSequenceUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: InviteSignature, into buf: inout [UInt8]) {
        FfiConverterSequenceUInt8.write(value.signature, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInviteSignature_lift(_ buf: RustBuffer) throws -> InviteSignature {
    return try FfiConverterTypeInviteSignature.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInviteSignature_lower(_ value: InviteSignature) -> RustBuffer {
    return FfiConverterTypeInviteSignature.lower(value)
}


public struct PowChallenge: Equatable, Hashable {
    public var challenge: String
    public var difficulty: UInt32
    public var expiresAt: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(challenge: String, difficulty: UInt32, expiresAt: Int64) {
        self.challenge = challenge
        self.difficulty = difficulty
        self.expiresAt = expiresAt
    }

    
}

#if compiler(>=6)
extension PowChallenge: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePowChallenge: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PowChallenge {
        return
            try PowChallenge(
                challenge: FfiConverterString.read(from: &buf), 
                difficulty: FfiConverterUInt32.read(from: &buf), 
                expiresAt: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: PowChallenge, into buf: inout [UInt8]) {
        FfiConverterString.write(value.challenge, into: &buf)
        FfiConverterUInt32.write(value.difficulty, into: &buf)
        FfiConverterInt64.write(value.expiresAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePowChallenge_lift(_ buf: RustBuffer) throws -> PowChallenge {
    return try FfiConverterTypePowChallenge.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePowChallenge_lower(_ value: PowChallenge) -> RustBuffer {
    return FfiConverterTypePowChallenge.lower(value)
}


public struct PowSolution: Equatable, Hashable {
    public var nonce: UInt64
    public var hash: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(nonce: UInt64, hash: String) {
        self.nonce = nonce
        self.hash = hash
    }

    
}

#if compiler(>=6)
extension PowSolution: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePowSolution: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PowSolution {
        return
            try PowSolution(
                nonce: FfiConverterUInt64.read(from: &buf), 
                hash: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: PowSolution, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.nonce, into: &buf)
        FfiConverterString.write(value.hash, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePowSolution_lift(_ buf: RustBuffer) throws -> PowSolution {
    return try FfiConverterTypePowSolution.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePowSolution_lower(_ value: PowSolution) -> RustBuffer {
    return FfiConverterTypePowSolution.lower(value)
}


public struct PrivateKeysJson: Equatable, Hashable {
    public var identitySecret: String
    public var signingSecret: String
    public var signedPrekeySecret: String
    public var prekeySignature: String
    public var suiteId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(identitySecret: String, signingSecret: String, signedPrekeySecret: String, prekeySignature: String, suiteId: String) {
        self.identitySecret = identitySecret
        self.signingSecret = signingSecret
        self.signedPrekeySecret = signedPrekeySecret
        self.prekeySignature = prekeySignature
        self.suiteId = suiteId
    }

    
}

#if compiler(>=6)
extension PrivateKeysJson: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePrivateKeysJson: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrivateKeysJson {
        return
            try PrivateKeysJson(
                identitySecret: FfiConverterString.read(from: &buf), 
                signingSecret: FfiConverterString.read(from: &buf), 
                signedPrekeySecret: FfiConverterString.read(from: &buf), 
                prekeySignature: FfiConverterString.read(from: &buf), 
                suiteId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: PrivateKeysJson, into buf: inout [UInt8]) {
        FfiConverterString.write(value.identitySecret, into: &buf)
        FfiConverterString.write(value.signingSecret, into: &buf)
        FfiConverterString.write(value.signedPrekeySecret, into: &buf)
        FfiConverterString.write(value.prekeySignature, into: &buf)
        FfiConverterString.write(value.suiteId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrivateKeysJson_lift(_ buf: RustBuffer) throws -> PrivateKeysJson {
    return try FfiConverterTypePrivateKeysJson.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrivateKeysJson_lower(_ value: PrivateKeysJson) -> RustBuffer {
    return FfiConverterTypePrivateKeysJson.lower(value)
}


public struct RegistrationBundleJson: Equatable, Hashable {
    public var identityPublic: String
    public var signedPrekeyPublic: String
    public var signature: String
    public var verifyingKey: String
    public var suiteId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(identityPublic: String, signedPrekeyPublic: String, signature: String, verifyingKey: String, suiteId: String) {
        self.identityPublic = identityPublic
        self.signedPrekeyPublic = signedPrekeyPublic
        self.signature = signature
        self.verifyingKey = verifyingKey
        self.suiteId = suiteId
    }

    
}

#if compiler(>=6)
extension RegistrationBundleJson: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRegistrationBundleJson: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RegistrationBundleJson {
        return
            try RegistrationBundleJson(
                identityPublic: FfiConverterString.read(from: &buf), 
                signedPrekeyPublic: FfiConverterString.read(from: &buf), 
                signature: FfiConverterString.read(from: &buf), 
                verifyingKey: FfiConverterString.read(from: &buf), 
                suiteId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: RegistrationBundleJson, into buf: inout [UInt8]) {
        FfiConverterString.write(value.identityPublic, into: &buf)
        FfiConverterString.write(value.signedPrekeyPublic, into: &buf)
        FfiConverterString.write(value.signature, into: &buf)
        FfiConverterString.write(value.verifyingKey, into: &buf)
        FfiConverterString.write(value.suiteId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRegistrationBundleJson_lift(_ buf: RustBuffer) throws -> RegistrationBundleJson {
    return try FfiConverterTypeRegistrationBundleJson.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRegistrationBundleJson_lower(_ value: RegistrationBundleJson) -> RustBuffer {
    return FfiConverterTypeRegistrationBundleJson.lower(value)
}


public struct SessionInitResult: Equatable, Hashable {
    public var sessionId: String
    public var decryptedMessage: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sessionId: String, decryptedMessage: String) {
        self.sessionId = sessionId
        self.decryptedMessage = decryptedMessage
    }

    
}

#if compiler(>=6)
extension SessionInitResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionInitResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionInitResult {
        return
            try SessionInitResult(
                sessionId: FfiConverterString.read(from: &buf), 
                decryptedMessage: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SessionInitResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.sessionId, into: &buf)
        FfiConverterString.write(value.decryptedMessage, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionInitResult_lift(_ buf: RustBuffer) throws -> SessionInitResult {
    return try FfiConverterTypeSessionInitResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionInitResult_lower(_ value: SessionInitResult) -> RustBuffer {
    return FfiConverterTypeSessionInitResult.lower(value)
}


public struct TimingConfig: Equatable, Hashable {
    public var heartbeatIntervalSec: UInt64
    public var heartbeatJitterMs: UInt64
    public var maxSendDelayMs: UInt64
    public var enabled: Bool
    public var batteryAware: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(heartbeatIntervalSec: UInt64, heartbeatJitterMs: UInt64, maxSendDelayMs: UInt64, enabled: Bool, batteryAware: Bool) {
        self.heartbeatIntervalSec = heartbeatIntervalSec
        self.heartbeatJitterMs = heartbeatJitterMs
        self.maxSendDelayMs = maxSendDelayMs
        self.enabled = enabled
        self.batteryAware = batteryAware
    }

    
}

#if compiler(>=6)
extension TimingConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTimingConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TimingConfig {
        return
            try TimingConfig(
                heartbeatIntervalSec: FfiConverterUInt64.read(from: &buf), 
                heartbeatJitterMs: FfiConverterUInt64.read(from: &buf), 
                maxSendDelayMs: FfiConverterUInt64.read(from: &buf), 
                enabled: FfiConverterBool.read(from: &buf), 
                batteryAware: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: TimingConfig, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.heartbeatIntervalSec, into: &buf)
        FfiConverterUInt64.write(value.heartbeatJitterMs, into: &buf)
        FfiConverterUInt64.write(value.maxSendDelayMs, into: &buf)
        FfiConverterBool.write(value.enabled, into: &buf)
        FfiConverterBool.write(value.batteryAware, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimingConfig_lift(_ buf: RustBuffer) throws -> TimingConfig {
    return try FfiConverterTypeTimingConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimingConfig_lower(_ value: TimingConfig) -> RustBuffer {
    return FfiConverterTypeTimingConfig.lower(value)
}


public enum CryptoError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case InitializationFailed(message: String)
    
    case SessionNotFound(message: String)
    
    case SessionInitializationFailed(message: String)
    
    case EncryptionFailed(message: String)
    
    case DecryptionFailed(message: String)
    
    case InvalidKeyData(message: String)
    
    case InvalidCiphertext(message: String)
    
    case SerializationFailed(message: String)
    
    case MessagePackDeserializationFailed(message: String)
    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension CryptoError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCryptoError: FfiConverterRustBuffer {
    typealias SwiftType = CryptoError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CryptoError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InitializationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .SessionNotFound(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .SessionInitializationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .EncryptionFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .DecryptionFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .InvalidKeyData(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .InvalidCiphertext(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .SerializationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .MessagePackDeserializationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CryptoError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .InitializationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .SessionNotFound(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .SessionInitializationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .EncryptionFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .DecryptionFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .InvalidKeyData(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .InvalidCiphertext(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))
        case .SerializationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(8))
        case .MessagePackDeserializationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(9))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCryptoError_lift(_ buf: RustBuffer) throws -> CryptoError {
    return try FfiConverterTypeCryptoError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCryptoError_lower(_ value: CryptoError) -> RustBuffer {
    return FfiConverterTypeCryptoError.lower(value)
}




public protocol PowProgressCallback: AnyObject, Sendable {
    
    func onProgress(currentNonce: UInt64, attempts: UInt64, estimatedProgress: Float) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfacePowProgressCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfacePowProgressCallback] = [UniffiVTableCallbackInterfacePowProgressCallback(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfacePowProgressCallback.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface PowProgressCallback: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfacePowProgressCallback.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface PowProgressCallback: handle missing in uniffiClone")
            }
        },
        onProgress: { (
            uniffiHandle: UInt64,
            currentNonce: UInt64,
            attempts: UInt64,
            estimatedProgress: Float,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfacePowProgressCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onProgress(
                     currentNonce: try FfiConverterUInt64.lift(currentNonce),
                     attempts: try FfiConverterUInt64.lift(attempts),
                     estimatedProgress: try FfiConverterFloat.lift(estimatedProgress)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitPowProgressCallback() {
    uniffi_construct_core_fn_init_callback_vtable_powprogresscallback(UniffiCallbackInterfacePowProgressCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfacePowProgressCallback {
    fileprivate static let handleMap = UniffiHandleMap<PowProgressCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfacePowProgressCallback : FfiConverter {
    typealias SwiftType = PowProgressCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfacePowProgressCallback_lift(_ handle: UInt64) throws -> PowProgressCallback {
    return try FfiConverterCallbackInterfacePowProgressCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfacePowProgressCallback_lower(_ v: PowProgressCallback) -> UInt64 {
    return FfiConverterCallbackInterfacePowProgressCallback.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionCallbackInterfacePowProgressCallback: FfiConverterRustBuffer {
    typealias SwiftType = PowProgressCallback?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterCallbackInterfacePowProgressCallback.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterCallbackInterfacePowProgressCallback.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]

    public static func write(_ value: [UInt8], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt8.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt8] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt8]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt8.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}
public func batteryAwareJitterMs(baseMs: UInt64, maxJitterMs: UInt64, batteryLevel: Float) -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_construct_core_fn_func_battery_aware_jitter_ms(
        FfiConverterUInt64.lower(baseMs),
        FfiConverterUInt64.lower(maxJitterMs),
        FfiConverterFloat.lower(batteryLevel),$0
    )
})
}
public func computePow(challenge: String, difficulty: UInt32) -> PowSolution  {
    return try!  FfiConverterTypePowSolution_lift(try! rustCall() {
    uniffi_construct_core_fn_func_compute_pow(
        FfiConverterString.lower(challenge),
        FfiConverterUInt32.lower(difficulty),$0
    )
})
}
public func computePowWithProgress(challenge: String, difficulty: UInt32, progressCallback: PowProgressCallback?) -> PowSolution  {
    return try!  FfiConverterTypePowSolution_lift(try! rustCall() {
    uniffi_construct_core_fn_func_compute_pow_with_progress(
        FfiConverterString.lower(challenge),
        FfiConverterUInt32.lower(difficulty),
        FfiConverterOptionCallbackInterfacePowProgressCallback.lower(progressCallback),$0
    )
})
}
public func createCryptoCore()throws  -> ClassicCryptoCore  {
    return try  FfiConverterTypeClassicCryptoCore_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_construct_core_fn_func_create_crypto_core($0
    )
})
}
public func createCryptoCoreFromKeysJson(keysJson: String)throws  -> ClassicCryptoCore  {
    return try  FfiConverterTypeClassicCryptoCore_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_construct_core_fn_func_create_crypto_core_from_keys_json(
        FfiConverterString.lower(keysJson),$0
    )
})
}
public func deriveDeviceId(identityPublicKey: [UInt8]) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_construct_core_fn_func_derive_device_id(
        FfiConverterSequenceUInt8.lower(identityPublicKey),$0
    )
})
}
public func deriveVerifyingKeyFromSecret(identitySecretKey: [UInt8])throws  -> [UInt8]  {
    return try  FfiConverterSequenceUInt8.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_construct_core_fn_func_derive_verifying_key_from_secret(
        FfiConverterSequenceUInt8.lower(identitySecretKey),$0
    )
})
}
public func formatFederatedId(deviceId: String, serverHostname: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_construct_core_fn_func_format_federated_id(
        FfiConverterString.lower(deviceId),
        FfiConverterString.lower(serverHostname),$0
    )
})
}
public func generateDummyMessage(size: UInt64) -> [UInt8]  {
    return try!  FfiConverterSequenceUInt8.lift(try! rustCall() {
    uniffi_construct_core_fn_func_generate_dummy_message(
        FfiConverterUInt64.lower(size),$0
    )
})
}
public func generateEphemeralKeypair()throws  -> EphemeralKeyPair  {
    return try  FfiConverterTypeEphemeralKeyPair_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_construct_core_fn_func_generate_ephemeral_keypair($0
    )
})
}
public func heartbeatIntervalMs(baseIntervalSec: UInt64) -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_construct_core_fn_func_heartbeat_interval_ms(
        FfiConverterUInt64.lower(baseIntervalSec),$0
    )
})
}
public func isDummyMessage(data: [UInt8]) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_construct_core_fn_func_is_dummy_message(
        FfiConverterSequenceUInt8.lower(data),$0
    )
})
}
public func jitteredIntervalMs(baseMs: UInt64, jitterMs: UInt64) -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_construct_core_fn_func_jittered_interval_ms(
        FfiConverterUInt64.lower(baseMs),
        FfiConverterUInt64.lower(jitterMs),$0
    )
})
}
public func randomSendDelayMs(maxDelayMs: UInt64) -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_construct_core_fn_func_random_send_delay_ms(
        FfiConverterUInt64.lower(maxDelayMs),$0
    )
})
}
public func recommendedSendDelayMs(isHighPriority: Bool, batteryLevel: Float) -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_construct_core_fn_func_recommended_send_delay_ms(
        FfiConverterBool.lower(isHighPriority),
        FfiConverterFloat.lower(batteryLevel),$0
    )
})
}
public func signInviteData(data: String, identitySecretKey: [UInt8])throws  -> InviteSignature  {
    return try  FfiConverterTypeInviteSignature_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_construct_core_fn_func_sign_invite_data(
        FfiConverterString.lower(data),
        FfiConverterSequenceUInt8.lower(identitySecretKey),$0
    )
})
}
public func verifyInviteSignature(data: String, signature: [UInt8], verifyingKey: [UInt8])throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_construct_core_fn_func_verify_invite_signature(
        FfiConverterString.lower(data),
        FfiConverterSequenceUInt8.lower(signature),
        FfiConverterSequenceUInt8.lower(verifyingKey),$0
    )
})
}
public func verifyPow(challenge: String, solution: PowSolution, requiredDifficulty: UInt32) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_construct_core_fn_func_verify_pow(
        FfiConverterString.lower(challenge),
        FfiConverterTypePowSolution_lower(solution),
        FfiConverterUInt32.lower(requiredDifficulty),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_construct_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_construct_core_checksum_func_battery_aware_jitter_ms() != 100) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_compute_pow() != 52528) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_compute_pow_with_progress() != 63236) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_create_crypto_core() != 59945) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_create_crypto_core_from_keys_json() != 4455) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_derive_device_id() != 1055) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_derive_verifying_key_from_secret() != 31516) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_format_federated_id() != 19004) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_generate_dummy_message() != 52724) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_generate_ephemeral_keypair() != 59553) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_heartbeat_interval_ms() != 51594) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_is_dummy_message() != 41979) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_jittered_interval_ms() != 6840) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_random_send_delay_ms() != 9943) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_recommended_send_delay_ms() != 24315) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_sign_invite_data() != 47259) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_verify_invite_signature() != 39140) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_func_verify_pow() != 44600) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_decrypt_message() != 15129) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_encrypt_message() != 45977) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_export_private_keys_json() != 62808) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_export_registration_bundle_json() != 47405) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_export_session_json() != 62166) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_get_all_session_contact_ids() != 3313) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_import_session_json() != 8946) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_init_receiving_session() != 32989) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_init_session() != 20828) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_remove_session() != 11481) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_set_local_user_id() != 65330) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_classiccryptocore_sign_bundle_data() != 39138) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_trafficprotectionmanager_current_interval_ms() != 34869) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_trafficprotectionmanager_generate_dummy() != 59992) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_trafficprotectionmanager_get_metrics() != 5234) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_trafficprotectionmanager_is_currently_active() != 35027) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_trafficprotectionmanager_record_real_message_sent() != 27042) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_trafficprotectionmanager_reset_metrics() != 18109) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_trafficprotectionmanager_should_send_dummy() != 33097) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_trafficprotectionmanager_update_battery_level() != 31087) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_constructor_trafficprotectionmanager_new() != 21642) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_construct_core_checksum_method_powprogresscallback_on_progress() != 50608) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitPowProgressCallback()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureConstructCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all