# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from services import auth_service_pb2 as services_dot_auth__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in services/auth_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """AuthService - Authentication & session management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPowChallenge = channel.unary_unary(
                '/shared.proto.services.v1.AuthService/GetPowChallenge',
                request_serializer=services_dot_auth__service__pb2.GetPowChallengeRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.GetPowChallengeResponse.FromString,
                _registered_method=True)
        self.RegisterDevice = channel.unary_unary(
                '/shared.proto.services.v1.AuthService/RegisterDevice',
                request_serializer=services_dot_auth__service__pb2.RegisterDeviceRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.AuthTokensResponse.FromString,
                _registered_method=True)
        self.AuthenticateDevice = channel.unary_unary(
                '/shared.proto.services.v1.AuthService/AuthenticateDevice',
                request_serializer=services_dot_auth__service__pb2.AuthenticateDeviceRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.AuthTokensResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/shared.proto.services.v1.AuthService/RefreshToken',
                request_serializer=services_dot_auth__service__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.RefreshTokenResponse.FromString,
                _registered_method=True)
        self.VerifyToken = channel.unary_unary(
                '/shared.proto.services.v1.AuthService/VerifyToken',
                request_serializer=services_dot_auth__service__pb2.VerifyTokenRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.VerifyTokenResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/shared.proto.services.v1.AuthService/Logout',
                request_serializer=services_dot_auth__service__pb2.LogoutRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.SetRecoveryKey = channel.unary_unary(
                '/shared.proto.services.v1.AuthService/SetRecoveryKey',
                request_serializer=services_dot_auth__service__pb2.SetRecoveryKeyRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.SetRecoveryKeyResponse.FromString,
                _registered_method=True)
        self.GetRecoveryStatus = channel.unary_unary(
                '/shared.proto.services.v1.AuthService/GetRecoveryStatus',
                request_serializer=services_dot_auth__service__pb2.GetRecoveryStatusRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.GetRecoveryStatusResponse.FromString,
                _registered_method=True)
        self.RecoverAccount = channel.unary_unary(
                '/shared.proto.services.v1.AuthService/RecoverAccount',
                request_serializer=services_dot_auth__service__pb2.RecoverAccountRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.RecoverAccountResponse.FromString,
                _registered_method=True)
        self.GetSenderCertificate = channel.unary_unary(
                '/shared.proto.services.v1.AuthService/GetSenderCertificate',
                request_serializer=services_dot_auth__service__pb2.GetSenderCertificateRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.GetSenderCertificateResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """AuthService - Authentication & session management
    """

    def GetPowChallenge(self, request, context):
        """GetPoWChallenge - Anti-spam challenge for device registration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterDevice(self, request, context):
        """RegisterDevice - Passwordless device registration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthenticateDevice(self, request, context):
        """AuthenticateDevice - Passwordless device authentication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """RefreshToken - Refresh access token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyToken(self, request, context):
        """VerifyToken - Validate access token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Logout - Revoke session tokens
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRecoveryKey(self, request, context):
        """=========================================================================
        Account Recovery (Seed Phrase)
        =========================================================================

        SetRecoveryKey - Set recovery public key (derived from seed phrase)
        Called once during initial setup, cannot be changed later
        Recovery key = Ed25519 public key derived from BIP39 seed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecoveryStatus(self, request, context):
        """GetRecoveryStatus - Check if recovery is set up for account
        Called on app startup to show recovery setup prompt if needed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecoverAccount(self, request, context):
        """RecoverAccount - Recover account using seed phrase
        Proves ownership by signing challenge with recovery key
        Creates new device, revokes all existing sessions
        =========================================================================
        Sealed Sender Certificate Issuance
        =========================================================================
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSenderCertificate(self, request, context):
        """GetSenderCertificate - Get a signed sender certificate for sealed sender
        Certificate proves sender identity to recipients without revealing it to servers.
        Signed by this server's Ed25519 federation key.
        Client should cache the certificate for up to 24 hours.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPowChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPowChallenge,
                    request_deserializer=services_dot_auth__service__pb2.GetPowChallengeRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.GetPowChallengeResponse.SerializeToString,
            ),
            'RegisterDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDevice,
                    request_deserializer=services_dot_auth__service__pb2.RegisterDeviceRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.AuthTokensResponse.SerializeToString,
            ),
            'AuthenticateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthenticateDevice,
                    request_deserializer=services_dot_auth__service__pb2.AuthenticateDeviceRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.AuthTokensResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=services_dot_auth__service__pb2.RefreshTokenRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.RefreshTokenResponse.SerializeToString,
            ),
            'VerifyToken': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyToken,
                    request_deserializer=services_dot_auth__service__pb2.VerifyTokenRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.VerifyTokenResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=services_dot_auth__service__pb2.LogoutRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.LogoutResponse.SerializeToString,
            ),
            'SetRecoveryKey': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRecoveryKey,
                    request_deserializer=services_dot_auth__service__pb2.SetRecoveryKeyRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.SetRecoveryKeyResponse.SerializeToString,
            ),
            'GetRecoveryStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecoveryStatus,
                    request_deserializer=services_dot_auth__service__pb2.GetRecoveryStatusRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.GetRecoveryStatusResponse.SerializeToString,
            ),
            'RecoverAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.RecoverAccount,
                    request_deserializer=services_dot_auth__service__pb2.RecoverAccountRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.RecoverAccountResponse.SerializeToString,
            ),
            'GetSenderCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSenderCertificate,
                    request_deserializer=services_dot_auth__service__pb2.GetSenderCertificateRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.GetSenderCertificateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shared.proto.services.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shared.proto.services.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """AuthService - Authentication & session management
    """

    @staticmethod
    def GetPowChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.AuthService/GetPowChallenge',
            services_dot_auth__service__pb2.GetPowChallengeRequest.SerializeToString,
            services_dot_auth__service__pb2.GetPowChallengeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.AuthService/RegisterDevice',
            services_dot_auth__service__pb2.RegisterDeviceRequest.SerializeToString,
            services_dot_auth__service__pb2.AuthTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthenticateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.AuthService/AuthenticateDevice',
            services_dot_auth__service__pb2.AuthenticateDeviceRequest.SerializeToString,
            services_dot_auth__service__pb2.AuthTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.AuthService/RefreshToken',
            services_dot_auth__service__pb2.RefreshTokenRequest.SerializeToString,
            services_dot_auth__service__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.AuthService/VerifyToken',
            services_dot_auth__service__pb2.VerifyTokenRequest.SerializeToString,
            services_dot_auth__service__pb2.VerifyTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.AuthService/Logout',
            services_dot_auth__service__pb2.LogoutRequest.SerializeToString,
            services_dot_auth__service__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRecoveryKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.AuthService/SetRecoveryKey',
            services_dot_auth__service__pb2.SetRecoveryKeyRequest.SerializeToString,
            services_dot_auth__service__pb2.SetRecoveryKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecoveryStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.AuthService/GetRecoveryStatus',
            services_dot_auth__service__pb2.GetRecoveryStatusRequest.SerializeToString,
            services_dot_auth__service__pb2.GetRecoveryStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecoverAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.AuthService/RecoverAccount',
            services_dot_auth__service__pb2.RecoverAccountRequest.SerializeToString,
            services_dot_auth__service__pb2.RecoverAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSenderCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.AuthService/GetSenderCertificate',
            services_dot_auth__service__pb2.GetSenderCertificateRequest.SerializeToString,
            services_dot_auth__service__pb2.GetSenderCertificateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DeviceServiceStub(object):
    """DeviceService - Device management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDevices = channel.unary_stream(
                '/shared.proto.services.v1.DeviceService/ListDevices',
                request_serializer=services_dot_auth__service__pb2.ListDevicesRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.DeviceInfo.FromString,
                _registered_method=True)
        self.RevokeDevice = channel.unary_unary(
                '/shared.proto.services.v1.DeviceService/RevokeDevice',
                request_serializer=services_dot_auth__service__pb2.RevokeDeviceRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.RevokeDeviceResponse.FromString,
                _registered_method=True)
        self.UpdatePushToken = channel.unary_unary(
                '/shared.proto.services.v1.DeviceService/UpdatePushToken',
                request_serializer=services_dot_auth__service__pb2.UpdatePushTokenRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.UpdatePushTokenResponse.FromString,
                _registered_method=True)
        self.UnregisterPushToken = channel.unary_unary(
                '/shared.proto.services.v1.DeviceService/UnregisterPushToken',
                request_serializer=services_dot_auth__service__pb2.UnregisterPushTokenRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.UnregisterPushTokenResponse.FromString,
                _registered_method=True)
        self.VerifyDevice = channel.unary_unary(
                '/shared.proto.services.v1.DeviceService/VerifyDevice',
                request_serializer=services_dot_auth__service__pb2.VerifyDeviceRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.VerifyDeviceResponse.FromString,
                _registered_method=True)
        self.GetDeviceInfo = channel.unary_unary(
                '/shared.proto.services.v1.DeviceService/GetDeviceInfo',
                request_serializer=services_dot_auth__service__pb2.GetDeviceInfoRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.DeviceInfo.FromString,
                _registered_method=True)
        self.InitiateDeviceLink = channel.unary_unary(
                '/shared.proto.services.v1.DeviceService/InitiateDeviceLink',
                request_serializer=services_dot_auth__service__pb2.InitiateDeviceLinkRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.InitiateDeviceLinkResponse.FromString,
                _registered_method=True)


class DeviceServiceServicer(object):
    """DeviceService - Device management
    """

    def ListDevices(self, request, context):
        """ListDevices - List all devices for current user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeDevice(self, request, context):
        """RevokeDevice - Revoke device (logout remotely)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePushToken(self, request, context):
        """UpdatePushToken - Update push notification token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterPushToken(self, request, context):
        """UnregisterPushToken - Remove push token when notifications are disabled or on logout
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyDevice(self, request, context):
        """VerifyDevice - Verify device (2FA)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceInfo(self, request, context):
        """GetDeviceInfo - Get specific device details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitiateDeviceLink(self, request, context):
        """=========================================================================
        Device Linking
        =========================================================================

        InitiateDeviceLink - Primary device generates a short-lived QR link token
        Authenticated: requires valid JWT from the primary/existing device
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDevices': grpc.unary_stream_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=services_dot_auth__service__pb2.ListDevicesRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.DeviceInfo.SerializeToString,
            ),
            'RevokeDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeDevice,
                    request_deserializer=services_dot_auth__service__pb2.RevokeDeviceRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.RevokeDeviceResponse.SerializeToString,
            ),
            'UpdatePushToken': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePushToken,
                    request_deserializer=services_dot_auth__service__pb2.UpdatePushTokenRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.UpdatePushTokenResponse.SerializeToString,
            ),
            'UnregisterPushToken': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterPushToken,
                    request_deserializer=services_dot_auth__service__pb2.UnregisterPushTokenRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.UnregisterPushTokenResponse.SerializeToString,
            ),
            'VerifyDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyDevice,
                    request_deserializer=services_dot_auth__service__pb2.VerifyDeviceRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.VerifyDeviceResponse.SerializeToString,
            ),
            'GetDeviceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceInfo,
                    request_deserializer=services_dot_auth__service__pb2.GetDeviceInfoRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.DeviceInfo.SerializeToString,
            ),
            'InitiateDeviceLink': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateDeviceLink,
                    request_deserializer=services_dot_auth__service__pb2.InitiateDeviceLinkRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.InitiateDeviceLinkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shared.proto.services.v1.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shared.proto.services.v1.DeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceService(object):
    """DeviceService - Device management
    """

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/shared.proto.services.v1.DeviceService/ListDevices',
            services_dot_auth__service__pb2.ListDevicesRequest.SerializeToString,
            services_dot_auth__service__pb2.DeviceInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.DeviceService/RevokeDevice',
            services_dot_auth__service__pb2.RevokeDeviceRequest.SerializeToString,
            services_dot_auth__service__pb2.RevokeDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePushToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.DeviceService/UpdatePushToken',
            services_dot_auth__service__pb2.UpdatePushTokenRequest.SerializeToString,
            services_dot_auth__service__pb2.UpdatePushTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterPushToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.DeviceService/UnregisterPushToken',
            services_dot_auth__service__pb2.UnregisterPushTokenRequest.SerializeToString,
            services_dot_auth__service__pb2.UnregisterPushTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.DeviceService/VerifyDevice',
            services_dot_auth__service__pb2.VerifyDeviceRequest.SerializeToString,
            services_dot_auth__service__pb2.VerifyDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.DeviceService/GetDeviceInfo',
            services_dot_auth__service__pb2.GetDeviceInfoRequest.SerializeToString,
            services_dot_auth__service__pb2.DeviceInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitiateDeviceLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.DeviceService/InitiateDeviceLink',
            services_dot_auth__service__pb2.InitiateDeviceLinkRequest.SerializeToString,
            services_dot_auth__service__pb2.InitiateDeviceLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DeviceLinkServiceStub(object):
    """DeviceLinkService - Device linking flow (separate service to avoid auth middleware)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConfirmDeviceLink = channel.unary_unary(
                '/shared.proto.services.v1.DeviceLinkService/ConfirmDeviceLink',
                request_serializer=services_dot_auth__service__pb2.ConfirmDeviceLinkRequest.SerializeToString,
                response_deserializer=services_dot_auth__service__pb2.AuthTokensResponse.FromString,
                _registered_method=True)


class DeviceLinkServiceServicer(object):
    """DeviceLinkService - Device linking flow (separate service to avoid auth middleware)
    """

    def ConfirmDeviceLink(self, request, context):
        """ConfirmDeviceLink - New device completes the link using the QR token
        NOT authenticated: new device has no JWT yet, uses link_token instead
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceLinkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConfirmDeviceLink': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmDeviceLink,
                    request_deserializer=services_dot_auth__service__pb2.ConfirmDeviceLinkRequest.FromString,
                    response_serializer=services_dot_auth__service__pb2.AuthTokensResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shared.proto.services.v1.DeviceLinkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shared.proto.services.v1.DeviceLinkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceLinkService(object):
    """DeviceLinkService - Device linking flow (separate service to avoid auth middleware)
    """

    @staticmethod
    def ConfirmDeviceLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.DeviceLinkService/ConfirmDeviceLink',
            services_dot_auth__service__pb2.ConfirmDeviceLinkRequest.SerializeToString,
            services_dot_auth__service__pb2.AuthTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
