# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from services import user_service_pb2 as services_dot_user__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in services/user_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """UserService - User profile & contact management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserProfile = channel.unary_unary(
                '/shared.proto.services.v1.UserService/GetUserProfile',
                request_serializer=services_dot_user__service__pb2.GetUserProfileRequest.SerializeToString,
                response_deserializer=services_dot_user__service__pb2.UserProfile.FromString,
                _registered_method=True)
        self.UpdateUserProfile = channel.unary_unary(
                '/shared.proto.services.v1.UserService/UpdateUserProfile',
                request_serializer=services_dot_user__service__pb2.UpdateUserProfileRequest.SerializeToString,
                response_deserializer=services_dot_user__service__pb2.UserProfile.FromString,
                _registered_method=True)
        self.UpdateProfilePicture = channel.unary_unary(
                '/shared.proto.services.v1.UserService/UpdateProfilePicture',
                request_serializer=services_dot_user__service__pb2.UpdateProfilePictureRequest.SerializeToString,
                response_deserializer=services_dot_user__service__pb2.UpdateProfilePictureResponse.FromString,
                _registered_method=True)
        self.GetUserCapabilities = channel.unary_unary(
                '/shared.proto.services.v1.UserService/GetUserCapabilities',
                request_serializer=services_dot_user__service__pb2.GetUserCapabilitiesRequest.SerializeToString,
                response_deserializer=services_dot_user__service__pb2.GetUserCapabilitiesResponse.FromString,
                _registered_method=True)
        self.BlockUser = channel.unary_unary(
                '/shared.proto.services.v1.UserService/BlockUser',
                request_serializer=services_dot_user__service__pb2.BlockUserRequest.SerializeToString,
                response_deserializer=services_dot_user__service__pb2.BlockUserResponse.FromString,
                _registered_method=True)
        self.UnblockUser = channel.unary_unary(
                '/shared.proto.services.v1.UserService/UnblockUser',
                request_serializer=services_dot_user__service__pb2.UnblockUserRequest.SerializeToString,
                response_deserializer=services_dot_user__service__pb2.UnblockUserResponse.FromString,
                _registered_method=True)
        self.GetBlockedUsers = channel.unary_unary(
                '/shared.proto.services.v1.UserService/GetBlockedUsers',
                request_serializer=services_dot_user__service__pb2.GetBlockedUsersRequest.SerializeToString,
                response_deserializer=services_dot_user__service__pb2.GetBlockedUsersResponse.FromString,
                _registered_method=True)
        self.DeleteAccount = channel.unary_unary(
                '/shared.proto.services.v1.UserService/DeleteAccount',
                request_serializer=services_dot_user__service__pb2.DeleteAccountRequest.SerializeToString,
                response_deserializer=services_dot_user__service__pb2.DeleteAccountResponse.FromString,
                _registered_method=True)
        self.ExportUserData = channel.unary_unary(
                '/shared.proto.services.v1.UserService/ExportUserData',
                request_serializer=services_dot_user__service__pb2.ExportUserDataRequest.SerializeToString,
                response_deserializer=services_dot_user__service__pb2.ExportUserDataResponse.FromString,
                _registered_method=True)
        self.CheckUsernameAvailability = channel.unary_unary(
                '/shared.proto.services.v1.UserService/CheckUsernameAvailability',
                request_serializer=services_dot_user__service__pb2.CheckUsernameAvailabilityRequest.SerializeToString,
                response_deserializer=services_dot_user__service__pb2.CheckUsernameAvailabilityResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """UserService - User profile & contact management
    """

    def GetUserProfile(self, request, context):
        """GetUserProfile - Fetch user profile
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserProfile(self, request, context):
        """UpdateUserProfile - Update own profile
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfilePicture(self, request, context):
        """UpdateProfilePicture - Upload profile picture
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserCapabilities(self, request, context):
        """GetUserCapabilities - Get user's device capabilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockUser(self, request, context):
        """BlockUser - Block another user for this account
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnblockUser(self, request, context):
        """UnblockUser - Remove user from blocklist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlockedUsers(self, request, context):
        """GetBlockedUsers - List blocked users
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAccount(self, request, context):
        """DeleteAccount - Delete user account (GDPR right to be forgotten)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportUserData(self, request, context):
        """ExportUserData - Export user data (GDPR data portability)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUsernameAvailability(self, request, context):
        """CheckUsernameAvailability - Check if username is available (no auth required)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProfile,
                    request_deserializer=services_dot_user__service__pb2.GetUserProfileRequest.FromString,
                    response_serializer=services_dot_user__service__pb2.UserProfile.SerializeToString,
            ),
            'UpdateUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserProfile,
                    request_deserializer=services_dot_user__service__pb2.UpdateUserProfileRequest.FromString,
                    response_serializer=services_dot_user__service__pb2.UserProfile.SerializeToString,
            ),
            'UpdateProfilePicture': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfilePicture,
                    request_deserializer=services_dot_user__service__pb2.UpdateProfilePictureRequest.FromString,
                    response_serializer=services_dot_user__service__pb2.UpdateProfilePictureResponse.SerializeToString,
            ),
            'GetUserCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserCapabilities,
                    request_deserializer=services_dot_user__service__pb2.GetUserCapabilitiesRequest.FromString,
                    response_serializer=services_dot_user__service__pb2.GetUserCapabilitiesResponse.SerializeToString,
            ),
            'BlockUser': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockUser,
                    request_deserializer=services_dot_user__service__pb2.BlockUserRequest.FromString,
                    response_serializer=services_dot_user__service__pb2.BlockUserResponse.SerializeToString,
            ),
            'UnblockUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UnblockUser,
                    request_deserializer=services_dot_user__service__pb2.UnblockUserRequest.FromString,
                    response_serializer=services_dot_user__service__pb2.UnblockUserResponse.SerializeToString,
            ),
            'GetBlockedUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlockedUsers,
                    request_deserializer=services_dot_user__service__pb2.GetBlockedUsersRequest.FromString,
                    response_serializer=services_dot_user__service__pb2.GetBlockedUsersResponse.SerializeToString,
            ),
            'DeleteAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAccount,
                    request_deserializer=services_dot_user__service__pb2.DeleteAccountRequest.FromString,
                    response_serializer=services_dot_user__service__pb2.DeleteAccountResponse.SerializeToString,
            ),
            'ExportUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportUserData,
                    request_deserializer=services_dot_user__service__pb2.ExportUserDataRequest.FromString,
                    response_serializer=services_dot_user__service__pb2.ExportUserDataResponse.SerializeToString,
            ),
            'CheckUsernameAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUsernameAvailability,
                    request_deserializer=services_dot_user__service__pb2.CheckUsernameAvailabilityRequest.FromString,
                    response_serializer=services_dot_user__service__pb2.CheckUsernameAvailabilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shared.proto.services.v1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shared.proto.services.v1.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """UserService - User profile & contact management
    """

    @staticmethod
    def GetUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.UserService/GetUserProfile',
            services_dot_user__service__pb2.GetUserProfileRequest.SerializeToString,
            services_dot_user__service__pb2.UserProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.UserService/UpdateUserProfile',
            services_dot_user__service__pb2.UpdateUserProfileRequest.SerializeToString,
            services_dot_user__service__pb2.UserProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfilePicture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.UserService/UpdateProfilePicture',
            services_dot_user__service__pb2.UpdateProfilePictureRequest.SerializeToString,
            services_dot_user__service__pb2.UpdateProfilePictureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.UserService/GetUserCapabilities',
            services_dot_user__service__pb2.GetUserCapabilitiesRequest.SerializeToString,
            services_dot_user__service__pb2.GetUserCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BlockUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.UserService/BlockUser',
            services_dot_user__service__pb2.BlockUserRequest.SerializeToString,
            services_dot_user__service__pb2.BlockUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnblockUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.UserService/UnblockUser',
            services_dot_user__service__pb2.UnblockUserRequest.SerializeToString,
            services_dot_user__service__pb2.UnblockUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlockedUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.UserService/GetBlockedUsers',
            services_dot_user__service__pb2.GetBlockedUsersRequest.SerializeToString,
            services_dot_user__service__pb2.GetBlockedUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.UserService/DeleteAccount',
            services_dot_user__service__pb2.DeleteAccountRequest.SerializeToString,
            services_dot_user__service__pb2.DeleteAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.UserService/ExportUserData',
            services_dot_user__service__pb2.ExportUserDataRequest.SerializeToString,
            services_dot_user__service__pb2.ExportUserDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUsernameAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.proto.services.v1.UserService/CheckUsernameAvailability',
            services_dot_user__service__pb2.CheckUsernameAvailabilityRequest.SerializeToString,
            services_dot_user__service__pb2.CheckUsernameAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
