// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct ClassicCryptoCore ClassicCryptoCore;
void __swift_bridge__$ClassicCryptoCore$_free(void* self);

void* __swift_bridge__$Vec_ClassicCryptoCore$new(void);
void __swift_bridge__$Vec_ClassicCryptoCore$drop(void* vec_ptr);
void __swift_bridge__$Vec_ClassicCryptoCore$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_ClassicCryptoCore$pop(void* vec_ptr);
void* __swift_bridge__$Vec_ClassicCryptoCore$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_ClassicCryptoCore$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_ClassicCryptoCore$len(void* vec_ptr);
void* __swift_bridge__$Vec_ClassicCryptoCore$as_ptr(void* vec_ptr);

typedef struct __swift_bridge__$RegistrationBundleB64 { void* identity_public; void* signed_prekey_public; void* signature; void* verifying_key; void* suite_id; } __swift_bridge__$RegistrationBundleB64;
typedef struct __swift_bridge__$Option$RegistrationBundleB64 { bool is_some; __swift_bridge__$RegistrationBundleB64 val; } __swift_bridge__$Option$RegistrationBundleB64;
struct __private__ResultPtrAndPtr __swift_bridge__$create_crypto_core(void);
void __swift_bridge__$destroy_crypto_core(void* core);
struct __swift_bridge__$ResultRegistrationBundleB64AndString __swift_bridge__$export_registration_bundle_b64(void* core);
struct __private__ResultPtrAndPtr __swift_bridge__$export_registration_bundle_json(void* core);
struct __private__ResultPtrAndPtr __swift_bridge__$init_session(void* core, struct RustStr contact_id, struct __private__FfiSlice recipient_bundle);
struct __private__ResultPtrAndPtr __swift_bridge__$encrypt_message(void* core, struct RustStr session_id, struct RustStr plaintext);
struct __private__ResultPtrAndPtr __swift_bridge__$decrypt_message(void* core, struct RustStr session_id, struct __private__FfiSlice ciphertext);
typedef enum __swift_bridge__$ResultRegistrationBundleB64AndString$Tag {__swift_bridge__$ResultRegistrationBundleB64AndString$ResultOk, __swift_bridge__$ResultRegistrationBundleB64AndString$ResultErr} __swift_bridge__$ResultRegistrationBundleB64AndString$Tag;
union __swift_bridge__$ResultRegistrationBundleB64AndString$Fields {struct __swift_bridge__$RegistrationBundleB64 ok; void* err;};
typedef struct __swift_bridge__$ResultRegistrationBundleB64AndString{__swift_bridge__$ResultRegistrationBundleB64AndString$Tag tag; union __swift_bridge__$ResultRegistrationBundleB64AndString$Fields payload;} __swift_bridge__$ResultRegistrationBundleB64AndString;


