//
//  CryptoManager.swift
//  Construct Messenger
//
//  Created by Maxim Eliseyev on 13.12.2025.
//  Updated for UniFFI clean API on 26.12.2025
//
//  This class is now a Swift wrapper around the UniFFI-generated Rust `construct-core` library.
//  Rust handles ALL crypto operations internally - Swift just passes wire format.
//

import Foundation
import CoreData
import os.log

class CryptoManager {
    static let shared = CryptoManager()

    // UniFFI ClassicCryptoCore object (automatically managed by Arc in Rust)
    private var core: ClassicCryptoCore?

    // Maps a user ID to a session ID generated by the Rust core
    private var userSessions: [String: String] = [:]
    // Maps a user ID to its associated suite ID
    private var userSuiteIds: [String: UInt16] = [:]

    private init() {
        do {
            // Try to load existing keys from Keychain
            if let savedKeysJson = KeychainManager.shared.loadPrivateKeysJson() {
                Log.info("🔑 Found existing keys in Keychain, restoring CryptoCore...", category: "CryptoManager")

                // Create CryptoCore from saved keys
                self.core = try createCryptoCoreFromKeysJson(keysJson: savedKeysJson)
                Log.info("✅ CryptoCore restored from saved keys!", category: "CryptoManager")
            } else {
                Log.info("🆕 No saved keys found, generating new CryptoCore...", category: "CryptoManager")

                // Create new CryptoCore with fresh keys
                self.core = try createCryptoCore()

                // Export private keys and save to Keychain
                if let core = self.core {
                    let keysJson = try core.exportPrivateKeysJson()
                    let saved = KeychainManager.shared.savePrivateKeysJson(keysJson)

                    if saved {
                        Log.info("✅ New CryptoCore created and keys saved to Keychain", category: "CryptoManager")
                    } else {
                        Log.error("⚠️ CryptoCore created but failed to save keys to Keychain", category: "CryptoManager")
                    }
                } else {
                    Log.error("❌ CryptoCore is nil after creation", category: "CryptoManager")
                }
            }
        } catch let error as CryptoError {
            // CryptoError is now the UniFFI-generated enum
            Log.fault("❌ Failed to create/restore UniFFI CryptoCore: \(error)", category: "CryptoManager")
            fatalError("Failed to create/restore UniFFI CryptoCore: \(error)")
        } catch {
            Log.fault("❌ Unexpected error creating/restoring CryptoCore: \(error)", category: "CryptoManager")
            fatalError("Unexpected error creating/restoring CryptoCore: \(error)")
        }

        // ✅ Restore recent sessions (pagination - first 10 chats)
        // ⚠️ Defer to avoid accessing Core Data before stores are loaded
        // This will be called later when Core Data is ready
        DispatchQueue.main.async { [weak self] in
            self?.restoreRecentSessions(limit: 10)
        }
    }

    // MARK: - Session Persistence

    /// Save session to Keychain after state change
    private func saveSessionToKeychain(for userId: String) {
        guard let core = core else { return }

        do {
            let sessionJson = try core.exportSessionJson(contactId: userId)
            let saved = KeychainManager.shared.saveSessionJson(sessionJson, for: userId)

            if saved {
                Log.debug("💾 Session saved to Keychain: \(userId)", category: "CryptoManager")
            } else {
                Log.debug("⚠️ Failed to save session to Keychain: \(userId)", category: "CryptoManager")
            }
        } catch {
            Log.error("❌ Session export failed: \(error)", category: "CryptoManager")
        }
    }

    /// Restore sessions for recent chats (pagination - first 10)
    func restoreRecentSessions(limit: Int = 10) {
        guard core != nil else {
            Log.error("Cannot restore sessions - core not initialized", category: "CryptoManager")
            return
        }

        // ✅ FIX: Check if Core Data is ready before accessing it
        let context = PersistenceController.shared.container.viewContext
        guard context.persistentStoreCoordinator != nil else {
            Log.info("⚠️ Core Data not ready yet, deferring session restore", category: "CryptoManager")
            // Retry after a short delay
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) { [weak self] in
                self?.restoreRecentSessions(limit: limit)
            }
            return
        }

        // Get recent chats from Core Data (sorted by lastMessageTime)
        let recentContactIds = getRecentChatContactIds(limit: limit)

        var restoredCount = 0
        var failedCount = 0

        for contactId in recentContactIds {
            if restoreSession(for: contactId) {
                restoredCount += 1
            } else {
                failedCount += 1
            }
        }

        Log.info("📦 Session restore: \(restoredCount) restored, \(failedCount) failed", category: "CryptoManager")
    }

    /// Restore a single session (used for lazy loading)
    @discardableResult
    func restoreSession(for userId: String) -> Bool {
        guard let core = core else { return false }

        // Skip if already in memory
        if userSessions[userId] != nil {
            return true
        }

        // Load from Keychain
        guard let sessionJson = KeychainManager.shared.loadSessionJson(for: userId) else {
            return false
        }

        do {
            let sessionId = try core.importSessionJson(contactId: userId, sessionJson: sessionJson)
            self.userSessions[userId] = sessionId
            Log.debug("✅ Restored session: \(userId)", category: "CryptoManager")
            return true
        } catch {
            Log.debug("⚠️ Failed to restore session for \(userId): \(error)", category: "CryptoManager")
            return false
        }
    }

    /// Get recent chat contact IDs from Core Data
    private func getRecentChatContactIds(limit: Int) -> [String] {
        let context = PersistenceController.shared.container.viewContext
        
        // ✅ FIX: Check if persistent store coordinator is ready before accessing entities
        guard context.persistentStoreCoordinator != nil else {
            Log.info("⚠️ Core Data persistent store coordinator not ready, skipping recent chats fetch", category: "CryptoManager")
            return []
        }
        
        let fetchRequest: NSFetchRequest<Chat> = Chat.fetchRequest()

        // Sort by last message time
        fetchRequest.sortDescriptors = [NSSortDescriptor(key: "lastMessageTime", ascending: false)]
        fetchRequest.fetchLimit = limit

        do {
            let chats = try context.fetch(fetchRequest)
            return chats.compactMap { $0.otherUser?.id }
        } catch {
            Log.error("Failed to fetch recent chats: \(error)", category: "CryptoManager")
            return []
        }
    }

    /// Get session ID for a user (for Core Data storage)
    func getSessionId(for userId: String) -> String? {
        return userSessions[userId]
    }

    deinit {
        // UniFFI manages memory automatically via Arc<T>
        // No manual cleanup needed!
    }

    // MARK: - Key Management

    /// Delete all saved cryptographic keys (e.g., on logout)
    /// After calling this, the app must be restarted to generate new keys
    func deleteAllCryptoKeys() {
        KeychainManager.shared.deletePrivateKeysJson()
        KeychainManager.shared.deleteAllKeys()
        Log.info("🗑️ All cryptographic keys deleted from Keychain", category: "CryptoManager")
    }

    // MARK: - Registration

    /// Generates a complete bundle for server registration by calling the Rust core.
    func generateRegistrationBundle() -> RegistrationBundle? {
        guard let core = core else { return nil }

        do {
            // UniFFI: Returns JSON string directly (no RustString wrapper!)
            let jsonString = try core.exportRegistrationBundleJson()

            // Parse JSON into Swift struct
            guard let jsonData = jsonString.data(using: .utf8) else {
                Log.error("Failed to convert JSON string to Data", category: "CryptoManager")
                return nil
            }

            let decoder = JSONDecoder()
            decoder.keyDecodingStrategy = .convertFromSnakeCase
            let bundle = try decoder.decode(RegistrationBundle.self, from: jsonData)

            Log.info("✅ Registration bundle generated successfully", category: "CryptoManager")
            return bundle
        } catch let error as CryptoError {
            Log.error("❌ Failed to generate registration bundle: \(error)", category: "CryptoManager")
            return nil
        } catch {
            Log.error("❌ Unexpected error generating bundle: \(error)", category: "CryptoManager")
            return nil
        }
    }
    
    /// Sign BundleData JSON with Ed25519 signing key
    /// This creates the signature for UploadableKeyBundle.bundleData
    func signBundleData(_ bundleDataJSON: Data) throws -> String {
        guard let core = core else {
            throw CryptoManagerError.coreNotInitialized
        }
        
        do {
            let bundleDataBytes = [UInt8](bundleDataJSON)
            let signatureBase64 = try core.signBundleData(bundleDataJson: bundleDataBytes)
            Log.debug("✅ BundleData signed successfully", category: "CryptoManager")
            return signatureBase64
        } catch let error as CryptoError {
            Log.error("❌ Failed to sign BundleData: \(error)", category: "CryptoManager")
            throw CryptoManagerError.invalidKeyData
        } catch {
            Log.error("❌ Unexpected error signing BundleData: \(error)", category: "CryptoManager")
            throw CryptoManagerError.invalidKeyData
        }
    }

    // MARK: - Session Management

    /// Initializes a secure session with a recipient using the Rust core.
    func initializeSession(for userId: String, recipientBundle: (identityPublic: String, signedPrekeyPublic: String, signature: String, verifyingKey: String, suiteId: String)) throws {
        guard let core = core else {
            throw CryptoManagerError.coreNotInitialized
        }
        
        // ✅ CRITICAL FIX: Force delete any existing session before initializing
        // This prevents session desynchronization when one party reinstalls app
        if userSessions[userId] != nil {
            Log.info("⚠️ Existing session found for \(userId) - deleting before reinitialization to prevent desync", category: "CryptoManager")
            deleteSession(for: userId)
        }

        // 1. Decode base64 strings to Data
        guard let identityPublicData = Data(base64Encoded: recipientBundle.identityPublic),
              let signedPrekeyPublicData = Data(base64Encoded: recipientBundle.signedPrekeyPublic),
              let signatureData = Data(base64Encoded: recipientBundle.signature),
              let verifyingKeyData = Data(base64Encoded: recipientBundle.verifyingKey)
        else {
            Log.error("Failed to decode base64-encoded keys from bundle", category: "CryptoManager")
            throw CryptoManagerError.invalidKeyData
        }

        // 2. Convert suiteId to UInt16
        guard let suiteID = UInt16(recipientBundle.suiteId) else {
            Log.error("Invalid suiteId format: \(recipientBundle.suiteId)", category: "CryptoManager")
            throw CryptoManagerError.invalidKeyData
        }

        // 3. Create the dictionary for JSON serialization
        let bundleDict: [String: Any] = [
            "identity_public": [UInt8](identityPublicData),
            "signed_prekey_public": [UInt8](signedPrekeyPublicData),
            "signature": [UInt8](signatureData),
            "verifying_key": [UInt8](verifyingKeyData),
            "suite_id": suiteID,
        ]

        do {
            let bundleData = try JSONSerialization.data(withJSONObject: bundleDict)
            let bytes = [UInt8](bundleData)

            // UniFFI: initSession returns String directly (no RustString!)
            let sessionId = try core.initSession(contactId: userId, recipientBundle: bytes)

            self.userSessions[userId] = sessionId
            self.userSuiteIds[userId] = suiteID
            Log.info("✅ Session initialized for user: \(userId)", category: "CryptoManager")

            // ✅ Auto-save session to Keychain
            saveSessionToKeychain(for: userId)
        } catch let error as CryptoError {
            // Log the full error details, including message if available
            var errorDetails = "❌ Failed to initialize session: \(error)"
            // Extract message from CryptoError if available
            let errorString = String(describing: error)
            if errorString.contains("message:") {
                errorDetails += " - Full error: \(errorString)"
            }
            Log.error(errorDetails, category: "CryptoManager")
            Log.error("   userId: \(userId)", category: "CryptoManager")
            Log.error("   identityPublic length: \(identityPublicData.count) bytes", category: "CryptoManager")
            Log.error("   identityPublic (base64): \(recipientBundle.identityPublic)", category: "CryptoManager")
            Log.error("   signedPrekeyPublic length: \(signedPrekeyPublicData.count) bytes", category: "CryptoManager")
            Log.error("   signedPrekeyPublic (base64): \(recipientBundle.signedPrekeyPublic)", category: "CryptoManager")
            Log.error("   signature length: \(signatureData.count) bytes", category: "CryptoManager")
            Log.error("   signature (base64): \(recipientBundle.signature)", category: "CryptoManager")
            Log.error("   verifyingKey length: \(verifyingKeyData.count) bytes", category: "CryptoManager")
            Log.error("   verifyingKey (base64): \(recipientBundle.verifyingKey)", category: "CryptoManager")
            Log.error("   suiteId: \(recipientBundle.suiteId)", category: "CryptoManager")
            throw CryptoManagerError.sessionInitializationFailed
        } catch {
            Log.error("❌ Unexpected error initializing session: \(error)", category: "CryptoManager")
            Log.error("   userId: \(userId)", category: "CryptoManager")
            throw CryptoManagerError.sessionInitializationFailed
        }
    }

    /// Check if a session exists for a user
    func hasSession(for userId: String) -> Bool {
        let exists = userSessions[userId] != nil
        Log.debug("🔑 Session check for \(userId): \(exists ? "EXISTS" : "MISSING")", category: "CryptoManager")
        if exists, let sessionId = userSessions[userId] {
            Log.debug("   Session ID: \(sessionId.prefix(16))...", category: "CryptoManager")
        }
        return exists
    }

    /// Delete a session for a user (called when deleting a chat)
    func deleteSession(for userId: String) {
        // Remove from the Swift session mapping
        if userSessions.removeValue(forKey: userId) != nil {
            Log.info("✅ Removed session from memory: \(userId)", category: "CryptoManager")
        }

        // Remove from the Rust core
        if let core = core {
            if core.removeSession(contactId: userId) {
                Log.info("✅ Removed session from Rust core: \(userId)", category: "CryptoManager")
            } else {
                Log.debug("No session found in Rust core for user \(userId)", category: "CryptoManager")
            }
        }

        // ✅ Remove from Keychain
        KeychainManager.shared.deleteSession(for: userId)
        Log.info("✅ Removed session from Keychain: \(userId)", category: "CryptoManager")
    }

    /// Initialize a receiving session (for responder/Bob) using sender's bundle + first message
    /// This is called when Bob receives the first message from Alice
    /// Returns the decrypted plaintext of the first message
    func initReceivingSession(for userId: String, recipientBundle: (identityPublic: String, signedPrekeyPublic: String, signature: String, verifyingKey: String, suiteId: String), firstMessage: ChatMessage) throws -> String {
        guard let core = core else {
            throw CryptoManagerError.coreNotInitialized
        }
        
        // ✅ CRITICAL FIX: Force delete any existing session before initializing
        // This ensures we start fresh and prevents Double Ratchet desynchronization
        if userSessions[userId] != nil {
            Log.info("⚠️ Existing session found for \(userId) - deleting before receiving session init to prevent desync", category: "CryptoManager")
            deleteSession(for: userId)
        }

        // 1. Decode base64 strings to Data
        guard let identityPublicData = Data(base64Encoded: recipientBundle.identityPublic),
              let signedPrekeyPublicData = Data(base64Encoded: recipientBundle.signedPrekeyPublic),
              let signatureData = Data(base64Encoded: recipientBundle.signature),
              let verifyingKeyData = Data(base64Encoded: recipientBundle.verifyingKey)
        else {
            Log.error("Failed to decode base64-encoded keys from bundle", category: "CryptoManager")
            throw CryptoManagerError.invalidKeyData
        }

        // 2. Convert suiteId to UInt16
        guard let suiteID = UInt16(recipientBundle.suiteId) else {
            Log.error("Invalid suiteId format: \(recipientBundle.suiteId)", category: "CryptoManager")
            throw CryptoManagerError.invalidKeyData
        }

        // 3. Create the bundle dictionary for JSON serialization
        let bundleDict: [String: Any] = [
            "identity_public": [UInt8](identityPublicData),
            "signed_prekey_public": [UInt8](signedPrekeyPublicData),
            "signature": [UInt8](signatureData),
            "verifying_key": [UInt8](verifyingKeyData),
            "suite_id": suiteID,
        ]

        // 4. Create the first message dictionary
        let messageDict: [String: Any] = [
            "ephemeral_public_key": [UInt8](firstMessage.ephemeralPublicKey),
            "message_number": firstMessage.messageNumber,
            "content": firstMessage.content  // Base64 string
        ]

        do {
            let bundleData = try JSONSerialization.data(withJSONObject: bundleDict)
            let bundleBytes = [UInt8](bundleData)

            let messageData = try JSONSerialization.data(withJSONObject: messageDict)
            let messageBytes = [UInt8](messageData)

            // ✅ NEW API: init_receiving_session returns SessionInitResult with decrypted message
            let result = try core.initReceivingSession(
                contactId: userId,
                recipientBundle: bundleBytes,
                firstMessage: messageBytes
            )

            self.userSessions[userId] = result.sessionId
            self.userSuiteIds[userId] = suiteID
            Log.info("✅ Receiving session initialized for user: \(userId), decrypted message length: \(result.decryptedMessage.count)", category: "CryptoManager")

            // ✅ Auto-save session to Keychain
            saveSessionToKeychain(for: userId)

            // Return the decrypted first message
            return result.decryptedMessage
        } catch let error as CryptoError {
            Log.error("❌ Failed to initialize receiving session: \(error)", category: "CryptoManager")
            throw CryptoManagerError.sessionInitializationFailed
        } catch {
            Log.error("❌ Unexpected error initializing receiving session: \(error)", category: "CryptoManager")
            throw CryptoManagerError.sessionInitializationFailed
        }
    }

    // MARK: - Encryption / Decryption

    /// Result of message encryption with separate fields per server ChatMessage spec
    struct EncryptedMessageComponents {
        let ephemeralPublicKey: Data  // dh_public_key (32 bytes) - sent as binary
        let messageNumber: UInt32
        let content: String  // Base64(nonce || ciphertext_with_tag)
        let suiteId: UInt16
    }

    /// Encrypts a plaintext message using the session for a specific user
    /// Returns separate components per server ChatMessage format
    func encryptMessage(_ message: String, for userId: String) throws -> EncryptedMessageComponents {
        guard let core = core else {
            throw CryptoManagerError.coreNotInitialized
        }

        // ✅ On-demand restore: Try to restore session if not in memory
        if userSessions[userId] == nil {
            Log.info("🔄 Session not in memory, attempting restore: \(userId)", category: "CryptoManager")

            if !restoreSession(for: userId) {
                throw CryptoManagerError.sessionNotFound
            }
        }

        guard let sessionId = userSessions[userId],
              let suiteId = userSuiteIds[userId] else {
            throw CryptoManagerError.sessionNotFound
        }

        do {
            // ✅ NEW CLEAN API: Rust returns wire format components directly
            let rustComponents = try core.encryptMessage(sessionId: sessionId, plaintext: message)

            // Convert to Swift struct
            let components = EncryptedMessageComponents(
                ephemeralPublicKey: Data(rustComponents.ephemeralPublicKey),
                messageNumber: rustComponents.messageNumber,
                content: rustComponents.content,
                suiteId: suiteId
            )

            Log.debug("✅ ENCRYPT: msgNum=\(components.messageNumber), ephemKey=\(rustComponents.ephemeralPublicKey.prefix(8).map { String(format: "%02x", $0) }.joined()), content=\(components.content.prefix(20))...", category: "CryptoManager")

            // ✅ Auto-save session after ratchet step
            saveSessionToKeychain(for: userId)

            return components
        } catch let error as CryptoError {
            Log.error("❌ Encryption failed (CryptoError): \(error)", category: "CryptoManager")
            Log.error("   Session ID: \(sessionId)", category: "CryptoManager")
            Log.error("   Message length: \(message.utf8.count) bytes", category: "CryptoManager")
            
            // Check if it's a session-related error that requires deletion
            // For now, delete session on any encryption error to allow reinitialization
            // TODO: Could be more selective based on error type
            Log.debug("🔄 Deleting session for \(userId) to allow reinitialization", category: "CryptoManager")
            deleteSession(for: userId)

            throw CryptoManagerError.encryptionFailed
        } catch {
            Log.error("❌ Unexpected encryption error: \(error)", category: "CryptoManager")
            Log.error("   Session ID: \(sessionId)", category: "CryptoManager")
            Log.error("   Message length: \(message.utf8.count) bytes", category: "CryptoManager")
            
            // Delete session on unexpected errors too
            Log.debug("🔄 Deleting session for \(userId) to allow reinitialization", category: "CryptoManager")
            deleteSession(for: userId)

            throw CryptoManagerError.encryptionFailed
        }
    }

    /// Decrypt a ChatMessage directly using clean API
    /// Uses clean API - Rust handles all MessagePack internally
    func decryptMessage(_ message: ChatMessage) throws -> String {
        guard let core = core else {
            throw CryptoManagerError.coreNotInitialized
        }

        // ✅ On-demand restore: Try to restore session if not in memory
        if userSessions[message.from] == nil {
            Log.info("🔄 Session not in memory, attempting restore: \(message.from)", category: "CryptoManager")

            if !restoreSession(for: message.from) {
                Log.error("❌ No session found for user: \(message.from)", category: "CryptoManager")
                throw CryptoManagerError.sessionNotFound
            }
        }

        guard let sessionId = userSessions[message.from] else {
            Log.error("❌ No session found for user: \(message.from)", category: "CryptoManager")
            throw CryptoManagerError.sessionNotFound
        }

        do {
            Log.debug("🔓 Decrypting message \(message.id.prefix(8))... from \(message.from.prefix(8))...", category: "CryptoManager")
            Log.debug("   messageNumber: \(message.messageNumber)", category: "CryptoManager")
            Log.debug("   ephemeralPublicKey: \(message.ephemeralPublicKey.count) bytes", category: "CryptoManager")
            Log.debug("   content length: \(message.content.count) chars", category: "CryptoManager")

            // ✅ NEW CLEAN API: Pass wire format components directly to Rust
            let plaintext = try core.decryptMessage(
                sessionId: sessionId,
                ephemeralPublicKey: [UInt8](message.ephemeralPublicKey),
                messageNumber: message.messageNumber,
                content: message.content
            )

            Log.info("✅ Message decrypted successfully (messageNumber: \(message.messageNumber), plaintext: \(plaintext.count) chars)", category: "CryptoManager")

            // ✅ Auto-save session after ratchet step
            saveSessionToKeychain(for: message.from)

            return plaintext
        } catch let error as CryptoError {
            Log.error("❌ Decryption failed for messageNumber \(message.messageNumber): \(error)", category: "CryptoManager")
            Log.error("   This usually means session desynchronization (sender and receiver out of sync)", category: "CryptoManager")

            // ✅ Auto-delete corrupted session to allow reinitialization
            Log.debug("🔄 Deleting corrupted session for \(message.from) to allow reinitialization", category: "CryptoManager")
            deleteSession(for: message.from)

            throw CryptoManagerError.decryptionFailed
        } catch {
            Log.error("❌ Unexpected decryption error: \(error)", category: "CryptoManager")

            // ✅ Auto-delete corrupted session to allow reinitialization
            Log.debug("🔄 Deleting corrupted session for \(message.from) to allow reinitialization", category: "CryptoManager")
            deleteSession(for: message.from)

            throw CryptoManagerError.decryptionFailed
        }
    }
}

// MARK: - Error Types

/// CryptoManager-specific errors (wraps UniFFI CryptoError)
enum CryptoManagerError: Error, LocalizedError {
    case coreNotInitialized
    case sessionNotFound
    case sessionInitializationFailed
    case encryptionFailed
    case decryptionFailed
    case invalidCiphertext
    case invalidKeyData

    var errorDescription: String? {
        switch self {
        case .coreNotInitialized:
            return "Crypto core is not initialized"
        case .sessionNotFound:
            return "No session found for this user"
        case .sessionInitializationFailed:
            return "Failed to initialize session"
        case .encryptionFailed:
            return "Failed to encrypt message"
        case .decryptionFailed:
            return "Failed to decrypt message"
        case .invalidCiphertext:
            return "Invalid ciphertext format"
        case .invalidKeyData:
            return "Invalid key data"
        }
    }
}
