//
//  CryptoManager.swift
//  Construct Messenger
//
//  Created by Maxim Eliseyev on 13.12.2025.
//  Updated for UniFFI clean API on 26.12.2025
//
//  This class is now a Swift wrapper around the UniFFI-generated Rust `construct-core` library.
//  Rust handles ALL crypto operations internally - Swift just passes wire format.
//

import Foundation
import CoreData
import os.log

class CryptoManager {
    static let shared = CryptoManager()

    // UniFFI ClassicCryptoCore object (automatically managed by Arc in Rust)
    // ⚠️ Internal access for InviteGenerator (needs to export keys)
    internal var core: ClassicCryptoCore?

    // Maps a user ID to a session ID generated by the Rust core
    private var userSessions: [String: String] = [:]
    // Maps a user ID to its associated suite ID
    private var userSuiteIds: [String: UInt16] = [:]
    
    // MARK: - Session Archive
    
    /// Archived sessions for out-of-order message support
    private var archivedSessions: [String: [SessionArchive]] = [:]
    
    /// Maximum archived sessions per user
    private let maxArchivedSessions = 3
    
    /// How long to keep archived sessions (7 days)
    private let archiveRetentionDays = 7
    
    // MARK: - Prekey ID Tracking
    
    /// Tracked prekey IDs for reinstall detection
    private var trackedPreKeyIds: [String: String] = [:]  // userId -> preKeyId
    
    /// UserDefaults key for prekey tracking
    private let preKeyTrackingKey = "tracked_prekey_ids"
    
    // MARK: - Garbage Collection
    
    /// Timer for periodic archive cleanup (24 hours)
    private var gcTimer: Timer?
    
    /// GC interval (24 hours)
    private let gcIntervalSeconds: TimeInterval = 24 * 60 * 60

    private init() {
        do {
            // Try to load existing keys from Keychain
            if let savedKeysJson = KeychainManager.shared.loadPrivateKeysJson() {
                Log.info("🔑 Found existing keys in Keychain, restoring CryptoCore...", category: "CryptoManager")

                // Create CryptoCore from saved keys
                self.core = try createCryptoCoreFromKeysJson(keysJson: savedKeysJson)
                Log.info("✅ CryptoCore restored from saved keys!", category: "CryptoManager")
            } else {
                Log.info("🆕 No saved keys found, generating new CryptoCore...", category: "CryptoManager")

                // Create new CryptoCore with fresh keys
                self.core = try createCryptoCore()

                // Export private keys and save to Keychain
                if let core = self.core {
                    let keysJson = try core.exportPrivateKeysJson()
                    let saved = KeychainManager.shared.savePrivateKeysJson(keysJson)

                    if saved {
                        Log.info("✅ New CryptoCore created and keys saved to Keychain", category: "CryptoManager")
                    } else {
                        Log.error("⚠️ CryptoCore created but failed to save keys to Keychain", category: "CryptoManager")
                    }
                } else {
                    Log.error("❌ CryptoCore is nil after creation", category: "CryptoManager")
                }
            }
        } catch let error as CryptoError {
            // CryptoError is now the UniFFI-generated enum
            Log.fault("❌ Failed to create/restore UniFFI CryptoCore: \(error)", category: "CryptoManager")
            fatalError("Failed to create/restore UniFFI CryptoCore: \(error)")
        } catch {
            Log.fault("❌ Unexpected error creating/restoring CryptoCore: \(error)", category: "CryptoManager")
            fatalError("Unexpected error creating/restoring CryptoCore: \(error)")
        }

        // ✅ Restore recent sessions (pagination - first 10 chats)
        // ⚠️ Defer to avoid accessing Core Data before stores are loaded
        // This will be called later when Core Data is ready
        DispatchQueue.main.async { [weak self] in
            self?.restoreRecentSessions(limit: 10)
            // 🆕 Run garbage collection after restoring sessions
            self?.cleanupArchivedSessions()
            // 🆕 Load tracked prekey IDs from UserDefaults
            self?.loadTrackedPreKeyIds()
            // 🆕 Start periodic GC timer (24 hours)
            self?.startGarbageCollectionTimer()
        }
    }
    
    // MARK: - Garbage Collection
    
    /// Start periodic garbage collection timer (runs every 24 hours)
    private func startGarbageCollectionTimer() {
        gcTimer?.invalidate()  // Cancel existing timer if any
        
        gcTimer = Timer.scheduledTimer(withTimeInterval: gcIntervalSeconds, repeats: true) { [weak self] _ in
            Log.debug("🗑️ Running periodic archive garbage collection", category: "CryptoManager")
            self?.cleanupArchivedSessions()
        }
        
        // Add to RunLoop to ensure it fires even when app is in background
        if let timer = gcTimer {
            RunLoop.main.add(timer, forMode: .common)
        }
        
        Log.debug("⏰ Started archive GC timer (interval: 24h)", category: "CryptoManager")
    }
    
    deinit {
        // Stop GC timer on dealloc
        gcTimer?.invalidate()
        // UniFFI manages memory automatically via Arc<T>
        // No manual cleanup needed!
    }
    
    // MARK: - Prekey ID Tracking
    
    /// Load tracked prekey IDs from UserDefaults
    private func loadTrackedPreKeyIds() {
        if let data = UserDefaults.standard.data(forKey: preKeyTrackingKey),
           let decoded = try? JSONDecoder().decode([String: String].self, from: data) {
            trackedPreKeyIds = decoded
            Log.debug("📋 Loaded \(trackedPreKeyIds.count) tracked prekey IDs", category: "CryptoManager")
        }
    }
    
    /// Save tracked prekey IDs to UserDefaults
    private func saveTrackedPreKeyIds() {
        if let encoded = try? JSONEncoder().encode(trackedPreKeyIds) {
            UserDefaults.standard.set(encoded, forKey: preKeyTrackingKey)
        }
    }
    
    /// Track a prekey ID for a user and detect reinstall
    /// Returns true if prekey changed (potential reinstall detected)
    public func trackPreKeyId(_ preKeyId: String, for userId: String) -> Bool {
        let previousPreKeyId = trackedPreKeyIds[userId]
        
        // First time seeing this user or same prekey - no change
        if previousPreKeyId == nil {
            trackedPreKeyIds[userId] = preKeyId
            saveTrackedPreKeyIds()
            Log.debug("📝 Tracking prekey for \(userId): \(preKeyId.prefix(8))...", category: "CryptoManager")
            return false
        }
        
        // Prekey changed - potential reinstall!
        if previousPreKeyId != preKeyId {
            Log.info("⚠️ Prekey changed for \(userId): \(previousPreKeyId!.prefix(8))... -> \(preKeyId.prefix(8))...", category: "CryptoManager")
            Log.info("   This indicates app reinstall or key rotation", category: "CryptoManager")
            
            // Update tracked prekey
            trackedPreKeyIds[userId] = preKeyId
            saveTrackedPreKeyIds()
            
            // Archive existing session (if any)
            if hasSession(for: userId) {
                archiveSession(for: userId, reason: .preKeyChanged)
                Log.info("🗄️ Session archived due to prekey change", category: "CryptoManager")
            }
            
            return true  // Prekey changed!
        }
        
        return false  // No change
    }

    // MARK: - Session Persistence

    /// Save session to Keychain after state change
    private func saveSessionToKeychain(for userId: String) {
        guard let core = core else { return }

        do {
            let sessionJson = try core.exportSessionJson(contactId: userId)
            let saved = KeychainManager.shared.saveSessionJson(sessionJson, for: userId)

            if saved {
                Log.debug("💾 Session saved to Keychain: \(userId)", category: "CryptoManager")
            } else {
                Log.debug("⚠️ Failed to save session to Keychain: \(userId)", category: "CryptoManager")
            }
        } catch {
            Log.error("❌ Session export failed: \(error)", category: "CryptoManager")
        }
    }
    
    // MARK: - Session Archive Persistence
    
    /// Save archived sessions to Keychain
    private func saveArchivedSessionsToKeychain(for userId: String) {
        guard let archives = archivedSessions[userId] else { return }
        
        do {
            let encoder = JSONEncoder()
            encoder.dateEncodingStrategy = .iso8601
            let data = try encoder.encode(archives)
            
            let key = "session_archives_\(userId)"
            let saved = KeychainManager.shared.saveData(data, forKey: key)
            
            if saved {
                Log.debug("💾 Saved \(archives.count) archived sessions for \(userId)", category: "CryptoManager")
            } else {
                Log.error("❌ Failed to save archived sessions to Keychain", category: "CryptoManager")
            }
        } catch {
            Log.error("❌ Failed to encode archived sessions: \(error)", category: "CryptoManager")
        }
    }
    
    /// Load archived sessions from Keychain
    private func loadArchivedSessionsFromKeychain(for userId: String) -> [SessionArchive]? {
        let key = "session_archives_\(userId)"
        guard let data = KeychainManager.shared.loadData(forKey: key) else {
            return nil
        }
        
        do {
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .iso8601
            let archives = try decoder.decode([SessionArchive].self, from: data)
            Log.debug("📦 Loaded \(archives.count) archived sessions for \(userId)", category: "CryptoManager")
            return archives
        } catch {
            Log.error("❌ Failed to decode archived sessions: \(error)", category: "CryptoManager")
            return nil
        }
    }
    
    /// Clear all archived sessions for a user
    func clearArchivedSessions(for userId: String) {
        archivedSessions.removeValue(forKey: userId)
        
        let key = "session_archives_\(userId)"
        KeychainManager.shared.deleteData(forKey: key)
        
        Log.info("🗑️ Cleared all archived sessions for \(userId)", category: "CryptoManager")
    }
    
    /// Garbage collection: Remove archived sessions older than retention period
    /// Called on app launch and periodically
    func cleanupArchivedSessions() {
        let cutoffDate = Date().addingTimeInterval(-TimeInterval(archiveRetentionDays * 24 * 60 * 60))
        var totalRemoved = 0
        
        // Get all user IDs with archived sessions
        // Since we can't enumerate Keychain, we'll clean up what's in memory
        // and rely on lazy loading from Keychain
        for userId in archivedSessions.keys {
            guard var archives = archivedSessions[userId] else { continue }
            
            let beforeCount = archives.count
            archives.removeAll { $0.archivedAt < cutoffDate }
            let afterCount = archives.count
            let removed = beforeCount - afterCount
            
            if removed > 0 {
                archivedSessions[userId] = archives.isEmpty ? nil : archives
                saveArchivedSessionsToKeychain(for: userId)
                totalRemoved += removed
                Log.debug("🗑️ Removed \(removed) expired archives for \(userId)", category: "CryptoManager")
            }
        }
        
        if totalRemoved > 0 {
            Log.info("♻️ Garbage collection complete: removed \(totalRemoved) expired session archives", category: "CryptoManager")
        } else {
            Log.debug("✅ Garbage collection: no expired archives found", category: "CryptoManager")
        }
    }

    /// Restore sessions for recent chats (pagination - first 10)
    func restoreRecentSessions(limit: Int = 10) {
        guard core != nil else {
            Log.error("Cannot restore sessions - core not initialized", category: "CryptoManager")
            return
        }

        // ✅ FIX: Check if Core Data is ready before accessing it
        let context = PersistenceController.shared.container.viewContext
        guard context.persistentStoreCoordinator != nil else {
            Log.info("⚠️ Core Data not ready yet, deferring session restore", category: "CryptoManager")
            // Retry after a short delay
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) { [weak self] in
                self?.restoreRecentSessions(limit: limit)
            }
            return
        }

        // Get recent chats from Core Data (sorted by lastMessageTime)
        let recentContactIds = getRecentChatContactIds(limit: limit)

        var restoredCount = 0
        var failedCount = 0

        for contactId in recentContactIds {
            if restoreSession(for: contactId) {
                restoredCount += 1
            } else {
                failedCount += 1
            }
        }

        Log.info("📦 Session restore: \(restoredCount) restored, \(failedCount) failed", category: "CryptoManager")
    }

    /// Restore a single session (used for lazy loading)
    @discardableResult
    func restoreSession(for userId: String) -> Bool {
        guard let core = core else { return false }

        // Skip if already in memory
        if userSessions[userId] != nil {
            return true
        }

        // Load from Keychain
        guard let sessionJson = KeychainManager.shared.loadSessionJson(for: userId) else {
            return false
        }

        do {
            let sessionId = try core.importSessionJson(contactId: userId, sessionJson: sessionJson)
            self.userSessions[userId] = sessionId
            Log.debug("✅ Restored session: \(userId)", category: "CryptoManager")
            return true
        } catch {
            Log.debug("⚠️ Failed to restore session for \(userId): \(error)", category: "CryptoManager")
            return false
        }
    }

    /// Get recent chat contact IDs from Core Data
    private func getRecentChatContactIds(limit: Int) -> [String] {
        let context = PersistenceController.shared.container.viewContext
        
        // ✅ FIX: Check if persistent store coordinator is ready before accessing entities
        guard context.persistentStoreCoordinator != nil else {
            Log.info("⚠️ Core Data persistent store coordinator not ready, skipping recent chats fetch", category: "CryptoManager")
            return []
        }
        
        let fetchRequest: NSFetchRequest<Chat> = Chat.fetchRequest()

        // Sort by last message time
        fetchRequest.sortDescriptors = [NSSortDescriptor(key: "lastMessageTime", ascending: false)]
        fetchRequest.fetchLimit = limit

        do {
            let chats = try context.fetch(fetchRequest)
            return chats.compactMap { $0.otherUser?.id }
        } catch {
            Log.error("Failed to fetch recent chats: \(error)", category: "CryptoManager")
            return []
        }
    }

    /// Get session ID for a user (for Core Data storage)
    func getSessionId(for userId: String) -> String? {
        return userSessions[userId]
    }

    // MARK: - Key Management

    /// Delete all saved cryptographic keys (e.g., on logout)
    /// After calling this, the app must be restarted to generate new keys
    func deleteAllCryptoKeys() {
        KeychainManager.shared.deletePrivateKeysJson()
        KeychainManager.shared.deleteAllKeys()
        Log.info("🗑️ All cryptographic keys deleted from Keychain", category: "CryptoManager")
    }

    // MARK: - Registration

    /// Generates a complete bundle for server registration by calling the Rust core.
    func generateRegistrationBundle() -> RegistrationBundle? {
        guard let core = core else { return nil }

        do {
            // UniFFI: Returns JSON string directly (no RustString wrapper!)
            let jsonString = try core.exportRegistrationBundleJson()

            // Parse JSON into Swift struct
            guard let jsonData = jsonString.data(using: .utf8) else {
                Log.error("Failed to convert JSON string to Data", category: "CryptoManager")
                return nil
            }

            let decoder = JSONDecoder()
            decoder.keyDecodingStrategy = .convertFromSnakeCase
            let bundle = try decoder.decode(RegistrationBundle.self, from: jsonData)

            Log.info("✅ Registration bundle generated successfully", category: "CryptoManager")
            return bundle
        } catch let error as CryptoError {
            Log.error("❌ Failed to generate registration bundle: \(error)", category: "CryptoManager")
            return nil
        } catch {
            Log.error("❌ Unexpected error generating bundle: \(error)", category: "CryptoManager")
            return nil
        }
    }
    
    /// Sign BundleData JSON with Ed25519 signing key
    /// This creates the signature for UploadableKeyBundle.bundleData
    func signBundleData(_ bundleDataJSON: Data) throws -> String {
        guard let core = core else {
            throw CryptoManagerError.coreNotInitialized
        }
        
        do {
            let bundleDataBytes = [UInt8](bundleDataJSON)
            let signatureBase64 = try core.signBundleData(bundleDataJson: bundleDataBytes)
            Log.debug("✅ BundleData signed successfully", category: "CryptoManager")
            return signatureBase64
        } catch let error as CryptoError {
            Log.error("❌ Failed to sign BundleData: \(error)", category: "CryptoManager")
            throw CryptoManagerError.invalidKeyData
        } catch {
            Log.error("❌ Unexpected error signing BundleData: \(error)", category: "CryptoManager")
            throw CryptoManagerError.invalidKeyData
        }
    }

    // MARK: - Session Management

    /// Initializes a secure session with a recipient using the Rust core.
    func initializeSession(for userId: String, recipientBundle: (identityPublic: String, signedPrekeyPublic: String, signature: String, verifyingKey: String, suiteId: String)) throws {
        guard let core = core else {
            throw CryptoManagerError.coreNotInitialized
        }
        
        // ✅ CRITICAL FIX: Force delete any existing session before initializing
        // This prevents session desynchronization when one party reinstalls app
        if userSessions[userId] != nil {
            Log.info("⚠️ Existing session found for \(userId) - deleting before reinitialization to prevent desync", category: "CryptoManager")
            deleteSession(for: userId)
        }

        // 1. Decode base64 strings to Data
        guard let identityPublicData = Data(base64Encoded: recipientBundle.identityPublic),
              let signedPrekeyPublicData = Data(base64Encoded: recipientBundle.signedPrekeyPublic),
              let signatureData = Data(base64Encoded: recipientBundle.signature),
              let verifyingKeyData = Data(base64Encoded: recipientBundle.verifyingKey)
        else {
            Log.error("Failed to decode base64-encoded keys from bundle", category: "CryptoManager")
            throw CryptoManagerError.invalidKeyData
        }

        // 2. Convert suiteId to UInt16
        guard let suiteID = UInt16(recipientBundle.suiteId) else {
            Log.error("Invalid suiteId format: \(recipientBundle.suiteId)", category: "CryptoManager")
            throw CryptoManagerError.invalidKeyData
        }

        // 3. Create the dictionary for JSON serialization
        let bundleDict: [String: Any] = [
            "identity_public": [UInt8](identityPublicData),
            "signed_prekey_public": [UInt8](signedPrekeyPublicData),
            "signature": [UInt8](signatureData),
            "verifying_key": [UInt8](verifyingKeyData),
            "suite_id": suiteID,
        ]

        do {
            let bundleData = try JSONSerialization.data(withJSONObject: bundleDict)
            let bytes = [UInt8](bundleData)

            // UniFFI: initSession returns String directly (no RustString!)
            let sessionId = try core.initSession(contactId: userId, recipientBundle: bytes)

            self.userSessions[userId] = sessionId
            self.userSuiteIds[userId] = suiteID
            Log.info("✅ Session initialized for user: \(userId)", category: "CryptoManager")

            // ✅ Auto-save session to Keychain
            saveSessionToKeychain(for: userId)
        } catch let error as CryptoError {
            // Log the full error details, including message if available
            var errorDetails = "❌ Failed to initialize session: \(error)"
            // Extract message from CryptoError if available
            let errorString = String(describing: error)
            if errorString.contains("message:") {
                errorDetails += " - Full error: \(errorString)"
            }
            Log.error(errorDetails, category: "CryptoManager")
            Log.error("   userId: \(userId)", category: "CryptoManager")
            Log.error("   identityPublic length: \(identityPublicData.count) bytes", category: "CryptoManager")
            Log.error("   identityPublic (base64): \(recipientBundle.identityPublic)", category: "CryptoManager")
            Log.error("   signedPrekeyPublic length: \(signedPrekeyPublicData.count) bytes", category: "CryptoManager")
            Log.error("   signedPrekeyPublic (base64): \(recipientBundle.signedPrekeyPublic)", category: "CryptoManager")
            Log.error("   signature length: \(signatureData.count) bytes", category: "CryptoManager")
            Log.error("   signature (base64): \(recipientBundle.signature)", category: "CryptoManager")
            Log.error("   verifyingKey length: \(verifyingKeyData.count) bytes", category: "CryptoManager")
            Log.error("   verifyingKey (base64): \(recipientBundle.verifyingKey)", category: "CryptoManager")
            Log.error("   suiteId: \(recipientBundle.suiteId)", category: "CryptoManager")
            throw CryptoManagerError.sessionInitializationFailed
        } catch {
            Log.error("❌ Unexpected error initializing session: \(error)", category: "CryptoManager")
            Log.error("   userId: \(userId)", category: "CryptoManager")
            throw CryptoManagerError.sessionInitializationFailed
        }
    }

    /// Check if a session exists for a user
    func hasSession(for userId: String) -> Bool {
        let exists = userSessions[userId] != nil
        Log.debug("🔑 Session check for \(userId): \(exists ? "EXISTS" : "MISSING")", category: "CryptoManager")
        if exists, let sessionId = userSessions[userId] {
            Log.debug("   Session ID: \(sessionId.prefix(16))...", category: "CryptoManager")
        }
        return exists
    }
    
    /// Get all user IDs with active sessions
    /// Used for sending END_SESSION to all contacts on logout
    func getAllSessionUserIds() -> [String] {
        return Array(userSessions.keys)
    }

    /// Delete a session for a user (called when deleting a chat)
    /// Archive a session instead of deleting it
    /// Allows fallback decryption for out-of-order messages
    func archiveSession(for userId: String, reason: ArchiveReason) {
        guard let core = core else {
            Log.error("❌ Cannot archive session: Core not initialized", category: "CryptoManager")
            return
        }
        
        Log.info("📦 Archiving session for \(userId), reason: \(reason.rawValue)", category: "CryptoManager")
        
        // 1. Export current session to JSON
        do {
            let sessionJson = try core.exportSessionJson(contactId: userId)
            
            // 2. Create archive entry
            let archive = SessionArchive(
                sessionJson: sessionJson,
                archivedAt: Date(),
                reason: reason
            )
            
            // 3. Add to archives (keep max limit)
            var archives = archivedSessions[userId] ?? []
            archives.append(archive)
            
            // Keep only newest N archives
            if archives.count > maxArchivedSessions {
                archives = Array(archives.suffix(maxArchivedSessions))
                Log.debug("🗑️ Trimmed archives to max \(maxArchivedSessions)", category: "CryptoManager")
            }
            
            archivedSessions[userId] = archives
            
            // 4. Save archives to Keychain
            saveArchivedSessionsToKeychain(for: userId)
            
            Log.info("✅ Session archived (\(archives.count) total for user)", category: "CryptoManager")
            
        } catch {
            Log.error("❌ Failed to export session for archiving: \(error)", category: "CryptoManager")
        }
        
        // 5. Remove from active sessions
        userSessions.removeValue(forKey: userId)
        Log.info("✅ Removed session from memory: \(userId)", category: "CryptoManager")
        
        // 6. Remove from Rust core
        let removed = core.removeSession(contactId: userId)
        if removed {
            Log.info("✅ Removed session from Rust core: \(userId)", category: "CryptoManager")
        } else {
            Log.info("⚠️ Session not found in Rust core: \(userId)", category: "CryptoManager")
        }
        
        // 7. Remove from Keychain
        KeychainManager.shared.deleteSession(for: userId)
        Log.info("✅ Removed session from Keychain: \(userId)", category: "CryptoManager")
    }
    
    /// Delete a session (legacy - use archiveSession instead)
    @available(*, deprecated, message: "Use archiveSession() instead for better error recovery")
    func deleteSession(for userId: String) {
        // Remove from the Swift session mapping
        if userSessions.removeValue(forKey: userId) != nil {
            Log.info("✅ Removed session from memory: \(userId)", category: "CryptoManager")
        }

        // Remove from the Rust core
        if let core = core {
            if core.removeSession(contactId: userId) {
                Log.info("✅ Removed session from Rust core: \(userId)", category: "CryptoManager")
            } else {
                Log.debug("No session found in Rust core for user \(userId)", category: "CryptoManager")
            }
        }

        // ✅ Remove from Keychain
        KeychainManager.shared.deleteSession(for: userId)
        Log.info("✅ Removed session from Keychain: \(userId)", category: "CryptoManager")
    }

    /// Initialize a receiving session (for responder/Bob) using sender's bundle + first message
    /// This is called when Bob receives the first message from Alice
    /// Returns the decrypted plaintext of the first message
    func initReceivingSession(for userId: String, recipientBundle: (identityPublic: String, signedPrekeyPublic: String, signature: String, verifyingKey: String, suiteId: String), firstMessage: ChatMessage) throws -> String {
        guard let core = core else {
            throw CryptoManagerError.coreNotInitialized
        }
        
        // ✅ CRITICAL FIX: Force delete any existing session before initializing
        // This ensures we start fresh and prevents Double Ratchet desynchronization
        if userSessions[userId] != nil {
            Log.info("⚠️ Existing session found for \(userId) - deleting before receiving session init to prevent desync", category: "CryptoManager")
            deleteSession(for: userId)
        }

        // 1. Decode base64 strings to Data
        guard let identityPublicData = Data(base64Encoded: recipientBundle.identityPublic),
              let signedPrekeyPublicData = Data(base64Encoded: recipientBundle.signedPrekeyPublic),
              let signatureData = Data(base64Encoded: recipientBundle.signature),
              let verifyingKeyData = Data(base64Encoded: recipientBundle.verifyingKey)
        else {
            Log.error("Failed to decode base64-encoded keys from bundle", category: "CryptoManager")
            throw CryptoManagerError.invalidKeyData
        }

        // 2. Convert suiteId to UInt16
        guard let suiteID = UInt16(recipientBundle.suiteId) else {
            Log.error("Invalid suiteId format: \(recipientBundle.suiteId)", category: "CryptoManager")
            throw CryptoManagerError.invalidKeyData
        }

        // 3. Create the bundle dictionary for JSON serialization
        let bundleDict: [String: Any] = [
            "identity_public": [UInt8](identityPublicData),
            "signed_prekey_public": [UInt8](signedPrekeyPublicData),
            "signature": [UInt8](signatureData),
            "verifying_key": [UInt8](verifyingKeyData),
            "suite_id": suiteID,
        ]

        // 4. Create the first message dictionary
        let messageDict: [String: Any] = [
            "ephemeral_public_key": [UInt8](firstMessage.ephemeralPublicKey),
            "message_number": firstMessage.messageNumber,
            "content": firstMessage.content  // Base64 string
        ]

        do {
            let bundleData = try JSONSerialization.data(withJSONObject: bundleDict)
            let bundleBytes = [UInt8](bundleData)

            let messageData = try JSONSerialization.data(withJSONObject: messageDict)
            let messageBytes = [UInt8](messageData)

            // ✅ NEW API: init_receiving_session returns SessionInitResult with decrypted message
            let result = try core.initReceivingSession(
                contactId: userId,
                recipientBundle: bundleBytes,
                firstMessage: messageBytes
            )

            self.userSessions[userId] = result.sessionId
            self.userSuiteIds[userId] = suiteID
            Log.info("✅ Receiving session initialized for user: \(userId), decrypted message length: \(result.decryptedMessage.count)", category: "CryptoManager")

            // ✅ Auto-save session to Keychain
            saveSessionToKeychain(for: userId)

            // Return the decrypted first message
            return result.decryptedMessage
        } catch let error as CryptoError {
            Log.error("❌ Failed to initialize receiving session: \(error)", category: "CryptoManager")
            throw CryptoManagerError.sessionInitializationFailed
        } catch {
            Log.error("❌ Unexpected error initializing receiving session: \(error)", category: "CryptoManager")
            throw CryptoManagerError.sessionInitializationFailed
        }
    }

    // MARK: - Encryption / Decryption

    /// Result of message encryption with separate fields per server ChatMessage spec
    struct EncryptedMessageComponents {
        let ephemeralPublicKey: Data  // dh_public_key (32 bytes) - sent as binary
        let messageNumber: UInt32
        let content: String  // Base64(nonce || ciphertext_with_tag)
        let suiteId: UInt16
    }

    /// Encrypts a plaintext message using the session for a specific user
    /// Returns separate components per server ChatMessage format
    func encryptMessage(_ message: String, for userId: String) throws -> EncryptedMessageComponents {
        guard let core = core else {
            throw CryptoManagerError.coreNotInitialized
        }

        // ✅ On-demand restore: Try to restore session if not in memory
        if userSessions[userId] == nil {
            Log.info("🔄 Session not in memory, attempting restore: \(userId)", category: "CryptoManager")

            if !restoreSession(for: userId) {
                throw CryptoManagerError.sessionNotFound
            }
        }

        guard let sessionId = userSessions[userId],
              let suiteId = userSuiteIds[userId] else {
            throw CryptoManagerError.sessionNotFound
        }

        do {
            // ✅ NEW CLEAN API: Rust returns wire format components directly
            let rustComponents = try core.encryptMessage(sessionId: sessionId, plaintext: message)

            // Convert to Swift struct
            let components = EncryptedMessageComponents(
                ephemeralPublicKey: Data(rustComponents.ephemeralPublicKey),
                messageNumber: rustComponents.messageNumber,
                content: rustComponents.content,
                suiteId: suiteId
            )

            Log.debug("✅ ENCRYPT: msgNum=\(components.messageNumber), ephemKey=\(rustComponents.ephemeralPublicKey.prefix(8).map { String(format: "%02x", $0) }.joined()), content=\(components.content.prefix(20))...", category: "CryptoManager")

            // ✅ Auto-save session after ratchet step
            saveSessionToKeychain(for: userId)

            return components
        } catch let error as CryptoError {
            Log.error("❌ Encryption failed (CryptoError): \(error)", category: "CryptoManager")
            Log.error("   Session ID: \(sessionId)", category: "CryptoManager")
            Log.error("   Message length: \(message.utf8.count) bytes", category: "CryptoManager")
            
            // Check if it's a session-related error that requires archiving
            // Archive session to allow fallback with archived sessions
            Log.debug("🔄 Archiving session for \(userId) to allow reinitialization", category: "CryptoManager")
            archiveSession(for: userId, reason: .decryptionFailed)

            throw CryptoManagerError.encryptionFailed
        } catch {
            Log.error("❌ Unexpected encryption error: \(error)", category: "CryptoManager")
            Log.error("   Session ID: \(sessionId)", category: "CryptoManager")
            Log.error("   Message length: \(message.utf8.count) bytes", category: "CryptoManager")
            
            // Archive session on unexpected errors too
            Log.debug("🔄 Archiving session for \(userId) to allow reinitialization", category: "CryptoManager")
            archiveSession(for: userId, reason: .decryptionFailed)

            throw CryptoManagerError.encryptionFailed
        }
    }

    /// Decrypt a ChatMessage directly using clean API
    /// Uses clean API - Rust handles all MessagePack internally
    /// Now with Session Archive fallback support
    func decryptMessage(_ message: ChatMessage) throws -> String {
        guard let core = core else {
            throw CryptoManagerError.coreNotInitialized
        }

        // ✅ On-demand restore: Try to restore session if not in memory
        if userSessions[message.from] == nil {
            Log.info("🔄 Session not in memory, attempting restore: \(message.from)", category: "CryptoManager")

            if !restoreSession(for: message.from) {
                Log.error("❌ No session found for user: \(message.from)", category: "CryptoManager")
                throw CryptoManagerError.sessionNotFound
            }
        }

        guard let sessionId = userSessions[message.from] else {
            Log.error("❌ No session found for user: \(message.from)", category: "CryptoManager")
            throw CryptoManagerError.sessionNotFound
        }

        do {
            Log.debug("🔓 Decrypting message \(message.id.prefix(8))... from \(message.from.prefix(8))...", category: "CryptoManager")
            Log.debug("   messageNumber: \(message.messageNumber)", category: "CryptoManager")
            Log.debug("   ephemeralPublicKey: \(message.ephemeralPublicKey.count) bytes", category: "CryptoManager")
            Log.debug("   content length: \(message.content.count) chars", category: "CryptoManager")

            // ✅ NEW CLEAN API: Pass wire format components directly to Rust
            let plaintext = try core.decryptMessage(
                sessionId: sessionId,
                ephemeralPublicKey: [UInt8](message.ephemeralPublicKey),
                messageNumber: message.messageNumber,
                content: message.content
            )

            Log.info("✅ Message decrypted successfully (messageNumber: \(message.messageNumber), plaintext: \(plaintext.count) chars)", category: "CryptoManager")

            // ✅ Auto-save session after ratchet step
            saveSessionToKeychain(for: message.from)

            return plaintext
        } catch let error as CryptoError {
            Log.error("❌ Decryption failed for messageNumber \(message.messageNumber): \(error)", category: "CryptoManager")
            
            // 🆕 Try archived sessions before giving up
            if let plaintext = try? tryDecryptWithArchivedSessions(message: message) {
                Log.info("✅ Successfully decrypted with archived session!", category: "CryptoManager")
                return plaintext
            }
            
            Log.error("   This usually means session desynchronization (sender and receiver out of sync)", category: "CryptoManager")

            // ✅ Archive corrupted session (don't delete immediately)
            Log.debug("🔄 Archiving corrupted session for \(message.from) to allow reinitialization", category: "CryptoManager")
            archiveSession(for: message.from, reason: .decryptionFailed)

            throw CryptoManagerError.decryptionFailed
        } catch {
            Log.error("❌ Unexpected decryption error: \(error)", category: "CryptoManager")

            // ✅ Archive corrupted session
            Log.debug("🔄 Archiving corrupted session for \(message.from) to allow reinitialization", category: "CryptoManager")
            archiveSession(for: message.from, reason: .decryptionFailed)

            throw CryptoManagerError.decryptionFailed
        }
    }
    
    /// Try to decrypt message with archived sessions
    /// Returns plaintext if successful, throws if all archives fail
    private func tryDecryptWithArchivedSessions(message: ChatMessage) throws -> String {
        guard let core = core else {
            throw CryptoManagerError.coreNotInitialized
        }
        
        // Load archives from memory or Keychain
        var archives = archivedSessions[message.from]
        if archives == nil {
            archives = loadArchivedSessionsFromKeychain(for: message.from)
            if let loaded = archives {
                archivedSessions[message.from] = loaded
            }
        }
        
        guard let archives = archives, !archives.isEmpty else {
            Log.debug("📦 No archived sessions available for \(message.from)", category: "CryptoManager")
            throw CryptoManagerError.sessionNotFound
        }
        
        Log.info("📦 Trying \(archives.count) archived sessions for \(message.from)", category: "CryptoManager")
        
        // Try each archived session (newest first - already ordered)
        for (index, archive) in archives.enumerated().reversed() {
            do {
                // Temporarily restore archived session to Rust core
                _ = try core.importSessionJson(contactId: message.from, sessionJson: archive.sessionJson)
                
                // Try to decrypt
                let plaintext = try core.decryptMessage(
                    sessionId: message.from,  // contactId is used as sessionId
                    ephemeralPublicKey: [UInt8](message.ephemeralPublicKey),
                    messageNumber: message.messageNumber,
                    content: message.content
                )
                
                Log.info("✅ Decrypted with archived session #\(index) (archived at: \(archive.archivedAt))", category: "CryptoManager")
                
                // Success! Restore this session as current
                userSessions[message.from] = message.from
                saveSessionToKeychain(for: message.from)
                
                // Remove from archives (it's valid again)
                var updatedArchives = archivedSessions[message.from] ?? []
                updatedArchives.remove(at: index)
                archivedSessions[message.from] = updatedArchives
                saveArchivedSessionsToKeychain(for: message.from)
                
                Log.info("♻️ Restored archived session as current", category: "CryptoManager")
                
                return plaintext
                
            } catch {
                Log.debug("❌ Archive #\(index) failed: \(error)", category: "CryptoManager")
                continue
            }
        }
        
        Log.info("⚠️ All \(archives.count) archived sessions failed to decrypt", category: "CryptoManager")
        throw CryptoManagerError.decryptionFailed
    }
}

// MARK: - Error Types

/// CryptoManager-specific errors (wraps UniFFI CryptoError)
enum CryptoManagerError: Error, LocalizedError {
    case coreNotInitialized
    case sessionNotFound
    case sessionInitializationFailed
    case encryptionFailed
    case decryptionFailed
    case invalidCiphertext
    case invalidKeyData

    var errorDescription: String? {
        switch self {
        case .coreNotInitialized:
            return "Crypto core is not initialized"
        case .sessionNotFound:
            return "No session found for this user"
        case .sessionInitializationFailed:
            return "Failed to initialize session"
        case .encryptionFailed:
            return "Failed to encrypt message"
        case .decryptionFailed:
            return "Failed to decrypt message"
        case .invalidCiphertext:
            return "Invalid ciphertext format"
        case .invalidKeyData:
            return "Invalid key data"
        }
    }
}

// MARK: - Session Archive

/// Reason for archiving a session
enum ArchiveReason: String, Codable {
    case decryptionFailed = "decryption_failed"
    case endSessionReceived = "end_session_received"
    case manualReset = "manual_reset"
    case preKeyChanged = "prekey_changed"
}

/// Archived session data for fallback decryption
struct SessionArchive: Codable {
    let sessionJson: String  // Exported session from Rust
    let archivedAt: Date
    let reason: ArchiveReason
    
    /// Check if archive is expired (older than retention period)
    func isExpired(retentionDays: Int) -> Bool {
        let expirationDate = Calendar.current.date(byAdding: .day, value: retentionDays, to: archivedAt) ?? Date()
        return Date() > expirationDate
    }
}
