# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/identity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'core/identity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ore/identity.proto\x12\x14shared.proto.core.v1\"k\n\x06UserId\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x06\x64omain\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x19\n\x0c\x64isplay_name\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_domainB\x0f\n\r_display_nameJ\x04\x08\x04\x10\x10\"\xf1\x01\n\x08\x44\x65viceId\x12*\n\x04user\x18\x01 \x01(\x0b\x32\x1c.shared.proto.core.v1.UserId\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x36\n\x08platform\x18\x03 \x01(\x0e\x32$.shared.proto.core.v1.DevicePlatform\x12\x18\n\x0b\x64\x65vice_name\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x15\n\rregistered_at\x18\x05 \x01(\x03\x12\x11\n\tlast_seen\x18\x06 \x01(\x03\x12\x14\n\x0c\x63\x61pabilities\x18\x10 \x01(\rB\x0e\n\x0c_device_nameJ\x04\x08\x11\x10\x33*\xbc\x01\n\x0e\x44\x65vicePlatform\x12\x1f\n\x1b\x44\x45VICE_PLATFORM_UNSPECIFIED\x10\x00\x12\x17\n\x13\x44\x45VICE_PLATFORM_IOS\x10\x01\x12\x1b\n\x17\x44\x45VICE_PLATFORM_ANDROID\x10\x02\x12\x1b\n\x17\x44\x45VICE_PLATFORM_DESKTOP\x10\x03\x12\x17\n\x13\x44\x45VICE_PLATFORM_WEB\x10\x04\x12\x17\n\x13\x44\x45VICE_PLATFORM_BOT\x10\x05\"\x04\x08\x06\x10\x0f*\x87\x02\n\x12\x44\x65viceCapabilities\x12#\n\x1f\x44\x45VICE_CAPABILITIES_UNSPECIFIED\x10\x00\x12\x1e\n\x1a\x44\x45VICE_CAPABILITIES_WEBRTC\x10\x01\x12\x1b\n\x17\x44\x45VICE_CAPABILITIES_MLS\x10\x02\x12!\n\x1d\x44\x45VICE_CAPABILITIES_PQ_CRYPTO\x10\x04\x12%\n!DEVICE_CAPABILITIES_SEALED_SENDER\x10\x08\x12\x1c\n\x18\x44\x45VICE_CAPABILITIES_PUSH\x10\x10\x12\'\n#DEVICE_CAPABILITIES_BACKGROUND_SYNC\x10 b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.identity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICEPLATFORM']._serialized_start=399
  _globals['_DEVICEPLATFORM']._serialized_end=587
  _globals['_DEVICECAPABILITIES']._serialized_start=590
  _globals['_DEVICECAPABILITIES']._serialized_end=853
  _globals['_USERID']._serialized_start=45
  _globals['_USERID']._serialized_end=152
  _globals['_DEVICEID']._serialized_start=155
  _globals['_DEVICEID']._serialized_end=396
# @@protoc_insertion_point(module_scope)
